/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface AnalyticsDaypartDto {
  /** 0 = Sunday, station-local */
  weekday: number;
  /** 0-23, station-local */
  hour: number;
  avgConcurrent: number;
  episodeCount: number;
}
