/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface AnalyticsOverviewDto {
  /** Highest concurrent listeners in any episode in range */
  peakConcurrent: number;
  /** Sum of each episode's unique listeners. Counts a repeat listener once per episode. */
  cumulativeEpisodeReach: number;
  /** Total listening hours across the period */
  totalListeningHours: number;
  /** Mean engagement actions per episode */
  averageEngagementPerEpisode: number;
  /** Episodes with a snapshot in range */
  episodeCount: number;
}
