/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

/**
 * Against the immediately preceding window of equal length
 */
export type AnalyticsShowRankDtoTrend = typeof AnalyticsShowRankDtoTrend[keyof typeof AnalyticsShowRankDtoTrend];


export const AnalyticsShowRankDtoTrend = {
  up: 'up',
  down: 'down',
  flat: 'flat',
} as const;
