/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export type AnnouncementsPublicControllerListParams = {
/**
 * Default 20, max 100
 */
pageSize?: number;
/**
 * 1-based page number, default 1
 */
page?: number;
};
