/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { AnnouncementStaffDtoStatus } from './announcementStaffDtoStatus.ts';
import type { ResolvedActorDto } from './resolvedActorDto.ts';

export interface AnnouncementStaffDto {
  id: string;
  title: string;
  /** Derived from title; not unique alone — decorative, regenerated on title edit */
  slug: string;
  /** 8-char immutable unique id — never regenerated */
  publicId: string;
  content: string;
  status: AnnouncementStaffDtoStatus;
  isPinned: boolean;
  /** @nullable */
  featuredAt: string | null;
  /** @nullable */
  scheduledFor: string | null;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  rejectionReason: string | null;
  /** @nullable */
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  lastEditedAt: string | null;
  /** @nullable */
  createdBy: ResolvedActorDto | null;
  /** @nullable */
  reviewedBy: ResolvedActorDto | null;
  /** @nullable */
  publishedBy: ResolvedActorDto | null;
  /** @nullable */
  featuredBy: ResolvedActorDto | null;
  /** @nullable */
  lastEditedBy: ResolvedActorDto | null;
  photos: string[];
}
