/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { AnnouncementStaffDto } from './announcementStaffDto.ts';
import type { AnnouncementStaffPageDtoCountsByStatus } from './announcementStaffPageDtoCountsByStatus.ts';

export interface AnnouncementStaffPageDto {
  items: AnnouncementStaffDto[];
  total: number;
  /** Whole-table row count per status, e.g. {"DRAFT": 3, "PUBLISHED": 12} */
  countsByStatus: AnnouncementStaffPageDtoCountsByStatus;
  pinnedCount: number;
}
