/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export type AnnouncementStaffDtoStatus = typeof AnnouncementStaffDtoStatus[keyof typeof AnnouncementStaffDtoStatus];


export const AnnouncementStaffDtoStatus = {
  DRAFT: 'DRAFT',
  PENDING_REVIEW: 'PENDING_REVIEW',
  PUBLISHED: 'PUBLISHED',
  SCHEDULED: 'SCHEDULED',
  ARCHIVED: 'ARCHIVED',
  REJECTED: 'REJECTED',
} as const;
