/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface AnnouncementPublicDto {
  id: string;
  title: string;
  /** Derived from title; not unique alone — decorative, regenerated on title edit */
  slug: string;
  /** 8-char immutable unique id — never regenerated */
  publicId: string;
  content: string;
  isPinned: boolean;
  /** @nullable */
  publishedAt: string | null;
  photos: string[];
}
