/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { AppealDtoStatus } from './appealDtoStatus.ts';

export interface AppealDto {
  id: string;
  userId: string;
  /** @nullable */
  subjectStrikeId: string | null;
  text: string;
  status: AppealDtoStatus;
  /** @nullable */
  reviewedById: string | null;
  /** @nullable */
  writtenResponse: string | null;
  createdAt: string;
  /** @nullable */
  resolvedAt: string | null;
  /**
     * Subject (userId) handle
     * @nullable
     */
  handle: string | null;
  /**
     * Subject (userId) listener class
     * @nullable
     */
  class: string | null;
  /**
     * Subject (userId) role
     * @nullable
     */
  role: string | null;
}
