/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { AttendanceRowDtoOvertimeStatus } from './attendanceRowDtoOvertimeStatus.ts';
import type { AttendanceRowDtoStatus } from './attendanceRowDtoStatus.ts';

export interface AttendanceRowDto {
  /** @nullable */
  recordId: string | null;
  /** @nullable */
  episodeId: string | null;
  /** @nullable */
  scheduledFor: string | null;
  rosterId: string;
  displayName: string;
  /** @nullable */
  scheduled: string | null;
  /** @nullable */
  scheduledEnd: string | null;
  /** @nullable */
  showId: string | null;
  /** @nullable */
  timeIn: string | null;
  /** @nullable */
  timeOut: string | null;
  /** @nullable */
  onAirHours: number | null;
  status: AttendanceRowDtoStatus;
  lateMinutes: number;
  overtimeMinutes: number;
  overtimeStatus: AttendanceRowDtoOvertimeStatus;
  /** @nullable */
  overtimeApprovedById: string | null;
  /** @nullable */
  overtimeApprovedAt: string | null;
  /** @nullable */
  note: string | null;
}
