/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { AttendanceRowDtoStatus } from './attendanceRowDtoStatus.ts';

export interface AttendanceRowDto {
  /** @nullable */
  recordId: string | null;
  /** @nullable */
  episodeId: string | null;
  /** @nullable */
  showId: string | null;
  rosterId: string;
  displayName: string;
  /** @nullable */
  scheduled: string | null;
  /** @nullable */
  scheduledFor: string | null;
  /**
     * HH:MM scheduled end time
     * @nullable
     */
  scheduledEnd: string | null;
  /** @nullable */
  timeIn: string | null;
  /** @nullable */
  timeOut: string | null;
  /** @nullable */
  onAirHours: number | null;
  status: AttendanceRowDtoStatus;
  lateMinutes: number;
  /** Whole minutes past the effective end (measured) */
  overtimeMinutes: number;
  /**
     * Broadcast attribution start; null while waiting for handover
     * @nullable
     */
  onAirStartAt: string | null;
  overtimeApproved: boolean;
  /** @nullable */
  overtimeApprovalReason: string | null;
  /** @nullable */
  note: string | null;
}
