/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface CorrectAttendanceDto {
  /**
     * First broadcast start, distinct from arrival; null removes broadcast attribution
     * @nullable
     */
  onAirStartAt?: string | null;
  timeIn?: string;
  /** @nullable */
  timeOut?: string | null;
  note?: string;
  /** Reason for the correction */
  reason?: string;
}
