/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface CreateAttendanceDto {
  showId: string;
  rosterId: string;
  /** The exact scheduled show occurrence identity */
  scheduledFor: string;
  timeIn: string;
  /** @nullable */
  timeOut?: string | null;
  note?: string;
  reason: string;
}
