/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { CreatePollDtoVisibility } from './createPollDtoVisibility';

export interface CreatePollDto {
  /**
     * @minLength 1
     * @maxLength 200
     */
  question: string;
  /**
     * @minItems 2
     * @maxItems 6
     */
  options: string[];
  visibility?: CreatePollDtoVisibility;
}
