/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { DjActiveShowDto } from './djActiveShowDto.ts';

export interface DjPublicDto {
  id: string;
  displayName: string;
  /** @nullable */
  photoUrl: string | null;
  /** @nullable */
  bio: string | null;
  activeShows: DjActiveShowDto[];
}
