/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { PublicSnapshotAuthorDto } from './publicSnapshotAuthorDto.ts';

export interface EpisodeSnapshotChatMessageDto {
  id: string;
  content: string;
  asBooth: boolean;
  createdAt: string;
  /** @nullable */
  author: PublicSnapshotAuthorDto | null;
}
