/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { EpisodeSnapshotChatMessageDto } from './episodeSnapshotChatMessageDto.ts';
import type { EpisodeSnapshotReactionDto } from './episodeSnapshotReactionDto.ts';
import type { EpisodeSnapshotUpNextDto } from './episodeSnapshotUpNextDto.ts';
import type { PinnedTopicResponseDto } from './pinnedTopicResponseDto.ts';
import type { PollResponseDto } from './pollResponseDto.ts';

export interface EpisodeEngagementSnapshotDto {
  episodeId: string;
  capturedAt: string;
  recentChat: EpisodeSnapshotChatMessageDto[];
  polls: PollResponseDto[];
  /** @nullable */
  pinnedTopic: PinnedTopicResponseDto | null;
  reactions: EpisodeSnapshotReactionDto[];
  upNext: EpisodeSnapshotUpNextDto[];
}
