/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { EpisodeSnapshotUpNextDtoType } from './episodeSnapshotUpNextDtoType.ts';

export interface EpisodeSnapshotUpNextDto {
  id: string;
  type: EpisodeSnapshotUpNextDtoType;
  text: string;
  /** @nullable */
  recipient: string | null;
  createdAt: string;
  /** @nullable */
  by: string | null;
}
