/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { ExportMediaKitFormat } from './exportMediaKitFormat.ts';

export type ExportMediaKitParams = {
/**
 * ISO date, exclusive. Default: now.
 */
to?: string;
/**
 * ISO date, inclusive. Default: 30 days ago.
 */
from?: string;
format: ExportMediaKitFormat;
};
