/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { FilterEntryDtoTier } from './filterEntryDtoTier.ts';

export interface FilterEntryDto {
  id: string;
  /** Normalized form stored for matching */
  word: string;
  tier: FilterEntryDtoTier;
  addedById: string;
  createdAt: string;
}
