/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { GetStreamManifest200Reason } from './getStreamManifest200Reason.ts';
import type { GetStreamManifest200Status } from './getStreamManifest200Status.ts';
import type { GetStreamManifest200Type } from './getStreamManifest200Type.ts';

export type GetStreamManifest200 = {
  status: GetStreamManifest200Status;
  /** @nullable */
  reason: GetStreamManifest200Reason;
  type: GetStreamManifest200Type;
  /** @nullable */
  url: string | null;
  dj: string[];
  /** @nullable */
  episodeId: string | null;
};
