/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface LegalNoticeDto {
  key: string;
  version: string;
  effectiveDate: string;
  title: string;
  body: string;
  /** True while the text is unreviewed placeholder pending counsel. A client must not present a placeholder document as binding terms. */
  isPlaceholder: boolean;
}
