/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { ListenerNotificationDtoType } from './listenerNotificationDtoType.ts';

export interface ListenerNotificationDto {
  id: string;
  type: ListenerNotificationDtoType;
  title: string;
  body: string;
  isRead: boolean;
  /** @nullable */
  relatedId: string | null;
  createdAt: string;
}
