/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { MeDtoClass } from './meDtoClass.ts';
import type { MeDtoRole } from './meDtoRole.ts';

export interface MeDto {
  id: string;
  email: string;
  name: string;
  handle: string;
  /** @nullable */
  avatarUrl: string | null;
  class: MeDtoClass;
  role: MeDtoRole;
  emailVerified: boolean;
  notifyEmail: boolean;
  notifyInApp: boolean;
  /**
     * Stored year level; PATCH accepts an integer or null
     * @nullable
     */
  yearLevel: string | null;
  /** @nullable */
  college: string | null;
  /** @nullable */
  gender: string | null;
}
