/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { StrikeDto } from './strikeDto.ts';

export interface MeStandingDto {
  /** @nullable */
  mutedUntil: string | null;
  /** @nullable */
  muteReason: string | null;
  /** @nullable */
  bannedAt: string | null;
  /** @nullable */
  banReason: string | null;
  strikes: StrikeDto[];
}
