/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { MusicSourceDtoSource } from './musicSourceDtoSource.ts';

export interface MusicSourceDto {
  id: string;
  title: string;
  /** @nullable */
  artist: string | null;
  source: MusicSourceDtoSource;
  /** @nullable */
  attribution: string | null;
  /** @nullable */
  clearanceProof: string | null;
  createdAt: string;
}
