/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export type MusicSourceDtoSource = typeof MusicSourceDtoSource[keyof typeof MusicSourceDtoSource];


export const MusicSourceDtoSource = {
  CC: 'CC',
  PUBLIC_DOMAIN: 'PUBLIC_DOMAIN',
  ROYALTY_FREE: 'ROYALTY_FREE',
  ORIGINAL_STUDENT: 'ORIGINAL_STUDENT',
} as const;
