/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export type PostStreamHeartbeat200Status = typeof PostStreamHeartbeat200Status[keyof typeof PostStreamHeartbeat200Status];


export const PostStreamHeartbeat200Status = {
  LIVE: 'LIVE',
  STATION_ROTATION: 'STATION_ROTATION',
  OFF_AIR: 'OFF_AIR',
} as const;
