/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

/**
 * @nullable
 */
export type PostStreamHeartbeat200Reason = typeof PostStreamHeartbeat200Reason[keyof typeof PostStreamHeartbeat200Reason] | null;


export const PostStreamHeartbeat200Reason = {
  NO_ATTENDANCE: 'NO_ATTENDANCE',
  SOURCE_STALE: 'SOURCE_STALE',
  SEGMENT_STALE: 'SEGMENT_STALE',
  PUBLICATION_STALE: 'PUBLICATION_STALE',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
} as const;
