/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { PublicSettingDtoValue } from './publicSettingDtoValue.ts';

export interface PublicSettingDto {
  /** Dot-namespaced setting key, e.g. branding.stationName */
  key: string;
  /** Derived group, e.g. 'branding' or 'copy' */
  group: string;
  /** Stored value; any JSON-serializable type */
  value: PublicSettingDtoValue;
}
