/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { AppealDto } from './appealDto.ts';
import type { ReinstatementRequestDto } from './reinstatementRequestDto.ts';
import type { ReportDto } from './reportDto.ts';

export interface QueueDto {
  /** Open user-authored reports (real reporterId) */
  reports: ReportDto[];
  /** Open system watch-flags (reason starts 'watch:') */
  watchFlags: ReportDto[];
  appeals: AppealDto[];
  reinstatements: ReinstatementRequestDto[];
}
