/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { QueueActionResponseDtoStatus } from './queueActionResponseDtoStatus';

export interface QueueActionResponseDto {
  /** Queue item id (cuid) */
  id: string;
  status: QueueActionResponseDtoStatus;
  /** Whether a private queue receipt is emitted to the submitter */
  receipt: boolean;
}
