/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { ReinstatementRequestDtoStatus } from './reinstatementRequestDtoStatus.ts';

export interface ReinstatementRequestDto {
  id: string;
  userId: string;
  text: string;
  status: ReinstatementRequestDtoStatus;
  /** @nullable */
  approvedById: string | null;
  createdAt: string;
  /**
     * Subject (userId) handle
     * @nullable
     */
  handle: string | null;
  /**
     * Subject (userId) listener class
     * @nullable
     */
  class: string | null;
  /**
     * Subject (userId) role
     * @nullable
     */
  role: string | null;
}
