/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { ReportDtoStatus } from './reportDtoStatus.ts';

export interface ReportDto {
  id: string;
  /** Real reporter for user reports; the target user for system watch-flags */
  reporterId: string;
  /** @nullable */
  targetUserId: string | null;
  /** @nullable */
  targetMessageId: string | null;
  /** @nullable */
  reason: string | null;
  status: ReportDtoStatus;
  /** @nullable */
  resolvedById: string | null;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  /**
     * Reported (targetUserId) user handle
     * @nullable
     */
  targetHandle: string | null;
  /**
     * Reported (targetUserId) user listener class
     * @nullable
     */
  targetClass: string | null;
}
