/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { ScheduleTodayOccurrenceDtoStatus } from './scheduleTodayOccurrenceDtoStatus.ts';

export interface ScheduleTodayOccurrenceDto {
  showId: string;
  showName: string;
  slug: string;
  status: ScheduleTodayOccurrenceDtoStatus;
  originalStart: string;
  originalEnd: string;
  effectiveStart: string;
  effectiveEnd: string;
}
