/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { SettingDtoValue } from './settingDtoValue.ts';

export interface SettingDto {
  /** Dot-namespaced setting key, e.g. toggle.chatFreeze */
  key: string;
  /** Derived group, e.g. toggle/killswitch/branding/copy */
  group: string;
  /** Stored value; any JSON-serializable type */
  value: SettingDtoValue;
  /**
     * User id of the last writer
     * @nullable
     */
  updatedBy: string | null;
  updatedAt: string;
}
