/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { ShowOccurrenceAdminDtoStatus } from './showOccurrenceAdminDtoStatus.ts';

export interface ShowOccurrenceAdminDto {
  showId: string;
  showName: string;
  slug: string;
  /** Station-local YYYY-MM-DD */
  date: string;
  status: ShowOccurrenceAdminDtoStatus;
  originalStart: string;
  originalEnd: string;
  effectiveStart: string;
  effectiveEnd: string;
  /** @nullable */
  reason: string | null;
  /**
     * Episode id once anyone tapped in
     * @nullable
     */
  episodeId: string | null;
  /** An episode exists (started or pending) — changes are locked */
  locked: boolean;
}
