/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface ShowPublicListItemDto {
  id: string;
  name: string;
  slug: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  coverImage: string | null;
  /** @nullable */
  theme: string | null;
  tags: string[];
}
