/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { RosterRefDto } from './rosterRefDto.ts';
import type { ShowDtoCadence } from './showDtoCadence.ts';

export interface ShowDto {
  id: string;
  name: string;
  slug: string;
  /** @nullable */
  description: string | null;
  cadence: ShowDtoCadence;
  createdAt: string;
  updatedAt: string;
  roster: RosterRefDto[];
  /**
     * #106 hiatus start, YYYY-MM-DD
     * @nullable
     */
  hiatusFrom: string | null;
  /**
     * #106 hiatus end (inclusive), YYYY-MM-DD
     * @nullable
     */
  hiatusUntil: string | null;
  /** @nullable */
  hiatusReason: string | null;
}
