/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { StaffAuditEntryDtoMetadata } from './staffAuditEntryDtoMetadata.ts';

export interface StaffAuditEntryDto {
  id: string;
  actorId: string;
  action: string;
  /** @nullable */
  entity: string | null;
  /** @nullable */
  entityId: string | null;
  /** @nullable */
  metadata: StaffAuditEntryDtoMetadata;
  createdAt: string;
}
