/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { StaffMemberDtoStatus } from './staffMemberDtoStatus.ts';

export interface StaffMemberDto {
  id: string;
  name: string;
  email: string;
  handle: string;
  status: StaffMemberDtoStatus;
  joinedAt: string;
  /** @nullable */
  lastActionAt: string | null;
  /** @nullable */
  deactivatedAt: string | null;
}
