/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { StandingDtoKind } from './standingDtoKind.ts';
import type { StandingDtoLevel } from './standingDtoLevel.ts';

export interface StandingDto {
  strikeId: string;
  level: StandingDtoLevel;
  kind: StandingDtoKind;
  /** @nullable */
  mutedUntil: string | null;
  /** @nullable */
  bannedAt: string | null;
  strikeExpiresAt: string;
}
