/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export type StudioTodayShowDtoStatus = typeof StudioTodayShowDtoStatus[keyof typeof StudioTodayShowDtoStatus];


export const StudioTodayShowDtoStatus = {
  SCHEDULED: 'SCHEDULED',
  DELAYED: 'DELAYED',
  CANCELLED: 'CANCELLED',
  HIATUS: 'HIATUS',
  PENDING_HANDOVER: 'PENDING_HANDOVER',
  ON_AIR: 'ON_AIR',
  DONE: 'DONE',
  ENDED_EARLY: 'ENDED_EARLY',
} as const;
