/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { StudioTodayShowDtoStatus } from './studioTodayShowDtoStatus.ts';

export interface StudioTodayShowDto {
  /**
     * Episode id once anyone tapped in
     * @nullable
     */
  id: string | null;
  /** @nullable */
  showId: string | null;
  /**
     * Original (cadence) start
     * @nullable
     */
  scheduledFor: string | null;
  effectiveStart: string;
  effectiveEnd: string;
  status: StudioTodayShowDtoStatus;
  /** @nullable */
  showName: string | null;
  djs: string[];
}
