/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export type StudioTimeInResultDtoState = typeof StudioTimeInResultDtoState[keyof typeof StudioTimeInResultDtoState];


export const StudioTimeInResultDtoState = {
  ON_AIR: 'ON_AIR',
  PENDING_HANDOVER: 'PENDING_HANDOVER',
} as const;
