/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { StudioTimeInResultDtoState } from './studioTimeInResultDtoState.ts';
import type { StudioTimeInResultDtoStatus } from './studioTimeInResultDtoStatus.ts';

export interface StudioTimeInResultDto {
  episodeId: string;
  status: StudioTimeInResultDtoStatus;
  state: StudioTimeInResultDtoState;
}
