/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { SubmitQueueItemDtoType } from './submitQueueItemDtoType';

export interface SubmitQueueItemDto {
  type: SubmitQueueItemDtoType;
  /**
     * @minLength 1
     * @maxLength 500
     */
  text: string;
  /** @maxLength 120 */
  recipient?: string;
}
