/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface TimeOutDto {
  rosterId: string;
  /**
     * Withdraw only a still-pending check-in for this episode. Reject if handover already started it.
     * @minLength 1
     * @maxLength 128
     */
  expectedPendingEpisodeId?: string;
}
