/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { TimeOutStudio200Status } from './timeOutStudio200Status.ts';

export type TimeOutStudio200 = {
  status: TimeOutStudio200Status;
};
