/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateMeDto {
  handle?: string;
  /** @nullable */
  avatarUrl?: string | null;
  notifyEmail?: boolean;
  notifyInApp?: boolean;
  /** @nullable */
  yearLevel?: number | null;
  /** @nullable */
  college?: string | null;
  /** @nullable */
  gender?: string | null;
}
