/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { UsersControllerSearchUsersClass } from './usersControllerSearchUsersClass.ts';

export type UsersControllerSearchUsersParams = {
/**
 * Default 20, max 100
 */
pageSize?: number;
/**
 * 1-based page number, default 1
 */
page?: number;
class?: UsersControllerSearchUsersClass;
/**
 * Free-text match against handle/email/name
 */
q?: string;
};
