/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import type { UserStrikeDtoLevel } from './userStrikeDtoLevel.ts';

export interface UserStrikeDto {
  id: string;
  level: UserStrikeDtoLevel;
  reason: string;
  issuedById: string;
  expiresAt: string;
  createdAt: string;
  /** true if expiresAt is in the future as of the query */
  active: boolean;
}
