/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AnnouncementPublicDto,
  AnnouncementPublicPageDto,
  AnnouncementsPublicControllerListParams
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getAnnouncementsPublicControllerListUrl = (params?: AnnouncementsPublicControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/announcements?${stringifiedParams}` : `/api/announcements`
}

/**
 * @summary Public paginated list of PUBLISHED announcements — pinned first, then publishedAt desc
 */
export const announcementsPublicControllerList = async (params?: AnnouncementsPublicControllerListParams, options?: RequestInit): Promise<AnnouncementPublicPageDto> => {

  return customFetch<AnnouncementPublicPageDto>(getAnnouncementsPublicControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAnnouncementsPublicControllerListQueryKey = (params?: AnnouncementsPublicControllerListParams,) => {
    return [
    `/api/announcements`, ...(params ? [params] : [])
    ] as const;
    }


export const getAnnouncementsPublicControllerListQueryOptions = <TData = Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError = unknown>(params?: AnnouncementsPublicControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAnnouncementsPublicControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof announcementsPublicControllerList>>> = ({ signal }) => announcementsPublicControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AnnouncementsPublicControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof announcementsPublicControllerList>>>
export type AnnouncementsPublicControllerListQueryError = unknown


export function useAnnouncementsPublicControllerList<TData = Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError = unknown>(
 params: undefined |  AnnouncementsPublicControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof announcementsPublicControllerList>>,
          TError,
          Awaited<ReturnType<typeof announcementsPublicControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAnnouncementsPublicControllerList<TData = Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError = unknown>(
 params?: AnnouncementsPublicControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof announcementsPublicControllerList>>,
          TError,
          Awaited<ReturnType<typeof announcementsPublicControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAnnouncementsPublicControllerList<TData = Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError = unknown>(
 params?: AnnouncementsPublicControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public paginated list of PUBLISHED announcements — pinned first, then publishedAt desc
 */

export function useAnnouncementsPublicControllerList<TData = Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError = unknown>(
 params?: AnnouncementsPublicControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAnnouncementsPublicControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getAnnouncementsPublicControllerGetOneUrl = (ref: string,) => {




  return `/api/announcements/${ref}`
}

/**
 * @summary Public single PUBLISHED announcement by ref — resolves the trailing publicId of a `slug-publicId` address (AC-C9/AC-C10), falling back to a bare cuid (the pre-Slice-C contract). A stale slug still resolves; the response always carries the canonical slug/publicId. 404 (not 403) if unknown or not published, so existence is never leaked.
 */
export const announcementsPublicControllerGetOne = async (ref: string, options?: RequestInit): Promise<AnnouncementPublicDto> => {

  return customFetch<AnnouncementPublicDto>(getAnnouncementsPublicControllerGetOneUrl(ref),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAnnouncementsPublicControllerGetOneQueryKey = (ref: string,) => {
    return [
    `/api/announcements/${ref}`
    ] as const;
    }


export const getAnnouncementsPublicControllerGetOneQueryOptions = <TData = Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError = unknown>(ref: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAnnouncementsPublicControllerGetOneQueryKey(ref);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>> = ({ signal }) => announcementsPublicControllerGetOne(ref, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: ref !== null && ref !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AnnouncementsPublicControllerGetOneQueryResult = NonNullable<Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>>
export type AnnouncementsPublicControllerGetOneQueryError = unknown


export function useAnnouncementsPublicControllerGetOne<TData = Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError = unknown>(
 ref: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAnnouncementsPublicControllerGetOne<TData = Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError = unknown>(
 ref: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAnnouncementsPublicControllerGetOne<TData = Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError = unknown>(
 ref: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public single PUBLISHED announcement by ref — resolves the trailing publicId of a `slug-publicId` address (AC-C9/AC-C10), falling back to a bare cuid (the pre-Slice-C contract). A stale slug still resolves; the response always carries the canonical slug/publicId. 404 (not 403) if unknown or not published, so existence is never leaked.
 */

export function useAnnouncementsPublicControllerGetOne<TData = Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError = unknown>(
 ref: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof announcementsPublicControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAnnouncementsPublicControllerGetOneQueryOptions(ref,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






