/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ScheduleDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetWeeklyScheduleUrl = () => {




  return `/api/schedule`
}

/**
 * @summary Get public weekly schedule grid
 */
export const getWeeklySchedule = async ( options?: RequestInit): Promise<ScheduleDto> => {

  return customFetch<ScheduleDto>(getGetWeeklyScheduleUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWeeklyScheduleQueryKey = () => {
    return [
    `/api/schedule`
    ] as const;
    }


export const getGetWeeklyScheduleQueryOptions = <TData = Awaited<ReturnType<typeof getWeeklySchedule>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklySchedule>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWeeklyScheduleQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWeeklySchedule>>> = ({ signal }) => getWeeklySchedule({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWeeklySchedule>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWeeklyScheduleQueryResult = NonNullable<Awaited<ReturnType<typeof getWeeklySchedule>>>
export type GetWeeklyScheduleQueryError = unknown


export function useGetWeeklySchedule<TData = Awaited<ReturnType<typeof getWeeklySchedule>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklySchedule>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklySchedule>>,
          TError,
          Awaited<ReturnType<typeof getWeeklySchedule>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeeklySchedule<TData = Awaited<ReturnType<typeof getWeeklySchedule>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklySchedule>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklySchedule>>,
          TError,
          Awaited<ReturnType<typeof getWeeklySchedule>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeeklySchedule<TData = Awaited<ReturnType<typeof getWeeklySchedule>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklySchedule>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get public weekly schedule grid
 */

export function useGetWeeklySchedule<TData = Awaited<ReturnType<typeof getWeeklySchedule>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklySchedule>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWeeklyScheduleQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






