/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  RosterControllerListParams,
  RosterEntryDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getRosterControllerListUrl = (params?: RosterControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/roster?${stringifiedParams}` : `/api/roster`
}

/**
 * @summary List roster entries (DJs)
 */
export const rosterControllerList = async (params?: RosterControllerListParams, options?: RequestInit): Promise<RosterEntryDto[]> => {

  return customFetch<RosterEntryDto[]>(getRosterControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getRosterControllerListQueryKey = (params?: RosterControllerListParams,) => {
    return [
    `/api/roster`, ...(params ? [params] : [])
    ] as const;
    }


export const getRosterControllerListQueryOptions = <TData = Awaited<ReturnType<typeof rosterControllerList>>, TError = unknown>(params?: RosterControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRosterControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rosterControllerList>>> = ({ signal }) => rosterControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rosterControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RosterControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof rosterControllerList>>>
export type RosterControllerListQueryError = unknown


export function useRosterControllerList<TData = Awaited<ReturnType<typeof rosterControllerList>>, TError = unknown>(
 params: undefined |  RosterControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rosterControllerList>>,
          TError,
          Awaited<ReturnType<typeof rosterControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRosterControllerList<TData = Awaited<ReturnType<typeof rosterControllerList>>, TError = unknown>(
 params?: RosterControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rosterControllerList>>,
          TError,
          Awaited<ReturnType<typeof rosterControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRosterControllerList<TData = Awaited<ReturnType<typeof rosterControllerList>>, TError = unknown>(
 params?: RosterControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List roster entries (DJs)
 */

export function useRosterControllerList<TData = Awaited<ReturnType<typeof rosterControllerList>>, TError = unknown>(
 params?: RosterControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRosterControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getRosterControllerCreateUrl = () => {




  return `/api/roster`
}

/**
 * @summary Create a roster entry
 */
export const rosterControllerCreate = async ( options?: RequestInit): Promise<RosterEntryDto> => {

  return customFetch<RosterEntryDto>(getRosterControllerCreateUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getRosterControllerCreateQueryKey = () => {
    return [
    'POST', `/api/roster`
    ] as const;
    }


export const getRosterControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof rosterControllerCreate>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRosterControllerCreateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rosterControllerCreate>>> = ({ signal }) => rosterControllerCreate({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rosterControllerCreate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RosterControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof rosterControllerCreate>>>
export type RosterControllerCreateQueryError = unknown


export function useRosterControllerCreate<TData = Awaited<ReturnType<typeof rosterControllerCreate>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerCreate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rosterControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof rosterControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRosterControllerCreate<TData = Awaited<ReturnType<typeof rosterControllerCreate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerCreate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rosterControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof rosterControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRosterControllerCreate<TData = Awaited<ReturnType<typeof rosterControllerCreate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create a roster entry
 */

export function useRosterControllerCreate<TData = Awaited<ReturnType<typeof rosterControllerCreate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRosterControllerCreateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getRosterControllerUpdateUrl = (id: string,) => {




  return `/api/roster/${id}`
}

/**
 * @summary Update or archive a roster entry
 */
export const rosterControllerUpdate = async (id: string, options?: RequestInit): Promise<RosterEntryDto> => {

  return customFetch<RosterEntryDto>(getRosterControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getRosterControllerUpdateQueryKey = (id: string,) => {
    return [
    'PATCH', `/api/roster/${id}`
    ] as const;
    }


export const getRosterControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof rosterControllerUpdate>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRosterControllerUpdateQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rosterControllerUpdate>>> = ({ signal }) => rosterControllerUpdate(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rosterControllerUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RosterControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof rosterControllerUpdate>>>
export type RosterControllerUpdateQueryError = unknown


export function useRosterControllerUpdate<TData = Awaited<ReturnType<typeof rosterControllerUpdate>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rosterControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof rosterControllerUpdate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRosterControllerUpdate<TData = Awaited<ReturnType<typeof rosterControllerUpdate>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rosterControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof rosterControllerUpdate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRosterControllerUpdate<TData = Awaited<ReturnType<typeof rosterControllerUpdate>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update or archive a roster entry
 */

export function useRosterControllerUpdate<TData = Awaited<ReturnType<typeof rosterControllerUpdate>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rosterControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRosterControllerUpdateQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






