/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetEpisodeUrl = (id: string,) => {




  return `/api/episodes/${id}`
}

/**
 * @summary Get episode by id
 */
export const getEpisode = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getGetEpisodeUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetEpisodeQueryKey = (id: string,) => {
    return [
    `/api/episodes/${id}`
    ] as const;
    }


export const getGetEpisodeQueryOptions = <TData = Awaited<ReturnType<typeof getEpisode>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEpisodeQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEpisode>>> = ({ signal }) => getEpisode(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEpisodeQueryResult = NonNullable<Awaited<ReturnType<typeof getEpisode>>>
export type GetEpisodeQueryError = unknown


export function useGetEpisode<TData = Awaited<ReturnType<typeof getEpisode>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEpisode>>,
          TError,
          Awaited<ReturnType<typeof getEpisode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEpisode<TData = Awaited<ReturnType<typeof getEpisode>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEpisode>>,
          TError,
          Awaited<ReturnType<typeof getEpisode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEpisode<TData = Awaited<ReturnType<typeof getEpisode>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get episode by id
 */

export function useGetEpisode<TData = Awaited<ReturnType<typeof getEpisode>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEpisodeQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






