/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';

export const GetHealthResponse = zod.unknown()


export const GetHealthDbResponse = zod.unknown()


export const ListSettingsResponse = zod.unknown()


export const GetStreamManifestResponse = zod.unknown()
