/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConsentRecordDto,
  LegalNoticeDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetLegalNoticeUrl = (document: 'tos' | 'privacy',) => {




  return `/api/legal/${document}`
}

/**
 * @summary Versioned Terms of Service or Privacy Notice
 */
export const getLegalNotice = async (document: 'tos' | 'privacy', options?: RequestInit): Promise<LegalNoticeDto> => {

  return customFetch<LegalNoticeDto>(getGetLegalNoticeUrl(document),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLegalNoticeQueryKey = (document: 'tos' | 'privacy',) => {
    return [
    `/api/legal/${document}`
    ] as const;
    }


export const getGetLegalNoticeQueryOptions = <TData = Awaited<ReturnType<typeof getLegalNotice>>, TError = unknown>(document: 'tos' | 'privacy', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLegalNotice>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLegalNoticeQueryKey(document);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLegalNotice>>> = ({ signal }) => getLegalNotice(document, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: document !== null && document !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLegalNotice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLegalNoticeQueryResult = NonNullable<Awaited<ReturnType<typeof getLegalNotice>>>
export type GetLegalNoticeQueryError = unknown


export function useGetLegalNotice<TData = Awaited<ReturnType<typeof getLegalNotice>>, TError = unknown>(
 document: 'tos' | 'privacy', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLegalNotice>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLegalNotice>>,
          TError,
          Awaited<ReturnType<typeof getLegalNotice>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLegalNotice<TData = Awaited<ReturnType<typeof getLegalNotice>>, TError = unknown>(
 document: 'tos' | 'privacy', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLegalNotice>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLegalNotice>>,
          TError,
          Awaited<ReturnType<typeof getLegalNotice>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLegalNotice<TData = Awaited<ReturnType<typeof getLegalNotice>>, TError = unknown>(
 document: 'tos' | 'privacy', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLegalNotice>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Versioned Terms of Service or Privacy Notice
 */

export function useGetLegalNotice<TData = Awaited<ReturnType<typeof getLegalNotice>>, TError = unknown>(
 document: 'tos' | 'privacy', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLegalNotice>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLegalNoticeQueryOptions(document,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getListMyConsentsUrl = () => {




  return `/api/consent`
}

/**
 * @summary The caller’s consent history
 */
export const listMyConsents = async ( options?: RequestInit): Promise<ConsentRecordDto[]> => {

  return customFetch<ConsentRecordDto[]>(getListMyConsentsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMyConsentsQueryKey = () => {
    return [
    `/api/consent`
    ] as const;
    }


export const getListMyConsentsQueryOptions = <TData = Awaited<ReturnType<typeof listMyConsents>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyConsents>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMyConsentsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyConsents>>> = ({ signal }) => listMyConsents({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyConsents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMyConsentsQueryResult = NonNullable<Awaited<ReturnType<typeof listMyConsents>>>
export type ListMyConsentsQueryError = unknown


export function useListMyConsents<TData = Awaited<ReturnType<typeof listMyConsents>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyConsents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyConsents>>,
          TError,
          Awaited<ReturnType<typeof listMyConsents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyConsents<TData = Awaited<ReturnType<typeof listMyConsents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyConsents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyConsents>>,
          TError,
          Awaited<ReturnType<typeof listMyConsents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyConsents<TData = Awaited<ReturnType<typeof listMyConsents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyConsents>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller’s consent history
 */

export function useListMyConsents<TData = Awaited<ReturnType<typeof listMyConsents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyConsents>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMyConsentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGrantConsentUrl = () => {




  return `/api/consent`
}

/**
 * @summary Grant consent for a scope, evidenced with the served notice version
 */
export const grantConsent = async ( options?: RequestInit): Promise<ConsentRecordDto> => {

  return customFetch<ConsentRecordDto>(getGrantConsentUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getGrantConsentQueryKey = () => {
    return [
    'POST', `/api/consent`
    ] as const;
    }


export const getGrantConsentQueryOptions = <TData = Awaited<ReturnType<typeof grantConsent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof grantConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGrantConsentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof grantConsent>>> = ({ signal }) => grantConsent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof grantConsent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GrantConsentQueryResult = NonNullable<Awaited<ReturnType<typeof grantConsent>>>
export type GrantConsentQueryError = unknown


export function useGrantConsent<TData = Awaited<ReturnType<typeof grantConsent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof grantConsent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof grantConsent>>,
          TError,
          Awaited<ReturnType<typeof grantConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGrantConsent<TData = Awaited<ReturnType<typeof grantConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof grantConsent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof grantConsent>>,
          TError,
          Awaited<ReturnType<typeof grantConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGrantConsent<TData = Awaited<ReturnType<typeof grantConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof grantConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Grant consent for a scope, evidenced with the served notice version
 */

export function useGrantConsent<TData = Awaited<ReturnType<typeof grantConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof grantConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGrantConsentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getWithdrawConsentUrl = (scope: 'DEMOGRAPHICS',) => {




  return `/api/consent/${scope}`
}

/**
 * @summary Withdraw consent — the record is kept as evidence, never deleted
 */
export const withdrawConsent = async (scope: 'DEMOGRAPHICS', options?: RequestInit): Promise<ConsentRecordDto> => {

  return customFetch<ConsentRecordDto>(getWithdrawConsentUrl(scope),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getWithdrawConsentQueryKey = (scope: 'DEMOGRAPHICS',) => {
    return [
    'DELETE', `/api/consent/${scope}`
    ] as const;
    }


export const getWithdrawConsentQueryOptions = <TData = Awaited<ReturnType<typeof withdrawConsent>>, TError = unknown>(scope: 'DEMOGRAPHICS', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof withdrawConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWithdrawConsentQueryKey(scope);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof withdrawConsent>>> = ({ signal }) => withdrawConsent(scope, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: scope !== null && scope !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof withdrawConsent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WithdrawConsentQueryResult = NonNullable<Awaited<ReturnType<typeof withdrawConsent>>>
export type WithdrawConsentQueryError = unknown


export function useWithdrawConsent<TData = Awaited<ReturnType<typeof withdrawConsent>>, TError = unknown>(
 scope: 'DEMOGRAPHICS', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof withdrawConsent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof withdrawConsent>>,
          TError,
          Awaited<ReturnType<typeof withdrawConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWithdrawConsent<TData = Awaited<ReturnType<typeof withdrawConsent>>, TError = unknown>(
 scope: 'DEMOGRAPHICS', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof withdrawConsent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof withdrawConsent>>,
          TError,
          Awaited<ReturnType<typeof withdrawConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWithdrawConsent<TData = Awaited<ReturnType<typeof withdrawConsent>>, TError = unknown>(
 scope: 'DEMOGRAPHICS', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof withdrawConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Withdraw consent — the record is kept as evidence, never deleted
 */

export function useWithdrawConsent<TData = Awaited<ReturnType<typeof withdrawConsent>>, TError = unknown>(
 scope: 'DEMOGRAPHICS', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof withdrawConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWithdrawConsentQueryOptions(scope,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getExportMyDataUrl = () => {




  return `/api/me/data/export`
}

/**
 * @summary Everything the station holds that identifies the caller (access + portability)
 */
export const exportMyData = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getExportMyDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getExportMyDataQueryKey = () => {
    return [
    `/api/me/data/export`
    ] as const;
    }


export const getExportMyDataQueryOptions = <TData = Awaited<ReturnType<typeof exportMyData>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportMyDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportMyData>>> = ({ signal }) => exportMyData({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportMyData>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportMyDataQueryResult = NonNullable<Awaited<ReturnType<typeof exportMyData>>>
export type ExportMyDataQueryError = unknown


export function useExportMyData<TData = Awaited<ReturnType<typeof exportMyData>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMyData>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportMyData>>,
          TError,
          Awaited<ReturnType<typeof exportMyData>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportMyData<TData = Awaited<ReturnType<typeof exportMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMyData>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportMyData>>,
          TError,
          Awaited<ReturnType<typeof exportMyData>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportMyData<TData = Awaited<ReturnType<typeof exportMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Everything the station holds that identifies the caller (access + portability)
 */

export function useExportMyData<TData = Awaited<ReturnType<typeof exportMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportMyDataQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCorrectMyDataUrl = () => {




  return `/api/me/data`
}

/**
 * @summary Correct the caller’s own profile fields
 */
export const correctMyData = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getCorrectMyDataUrl(),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getCorrectMyDataQueryKey = () => {
    return [
    'PATCH', `/api/me/data`
    ] as const;
    }


export const getCorrectMyDataQueryOptions = <TData = Awaited<ReturnType<typeof correctMyData>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof correctMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCorrectMyDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof correctMyData>>> = ({ signal }) => correctMyData({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof correctMyData>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CorrectMyDataQueryResult = NonNullable<Awaited<ReturnType<typeof correctMyData>>>
export type CorrectMyDataQueryError = unknown


export function useCorrectMyData<TData = Awaited<ReturnType<typeof correctMyData>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof correctMyData>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof correctMyData>>,
          TError,
          Awaited<ReturnType<typeof correctMyData>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCorrectMyData<TData = Awaited<ReturnType<typeof correctMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof correctMyData>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof correctMyData>>,
          TError,
          Awaited<ReturnType<typeof correctMyData>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCorrectMyData<TData = Awaited<ReturnType<typeof correctMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof correctMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Correct the caller’s own profile fields
 */

export function useCorrectMyData<TData = Awaited<ReturnType<typeof correctMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof correctMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCorrectMyDataQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getEraseMyDataUrl = () => {




  return `/api/me/data`
}

/**
 * @summary Erase the caller’s account (anonymisation — see the privacy notice)
 */
export const eraseMyData = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getEraseMyDataUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getEraseMyDataQueryKey = () => {
    return [
    'DELETE', `/api/me/data`
    ] as const;
    }


export const getEraseMyDataQueryOptions = <TData = Awaited<ReturnType<typeof eraseMyData>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eraseMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEraseMyDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof eraseMyData>>> = ({ signal }) => eraseMyData({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eraseMyData>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EraseMyDataQueryResult = NonNullable<Awaited<ReturnType<typeof eraseMyData>>>
export type EraseMyDataQueryError = unknown


export function useEraseMyData<TData = Awaited<ReturnType<typeof eraseMyData>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eraseMyData>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eraseMyData>>,
          TError,
          Awaited<ReturnType<typeof eraseMyData>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEraseMyData<TData = Awaited<ReturnType<typeof eraseMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eraseMyData>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eraseMyData>>,
          TError,
          Awaited<ReturnType<typeof eraseMyData>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEraseMyData<TData = Awaited<ReturnType<typeof eraseMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eraseMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Erase the caller’s account (anonymisation — see the privacy notice)
 */

export function useEraseMyData<TData = Awaited<ReturnType<typeof eraseMyData>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eraseMyData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEraseMyDataQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






