/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ShowEpisodesDto,
  ShowPublicDto,
  ShowPublicListItemDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListShowsPublicUrl = () => {




  return `/api/shows`
}

/**
 * @summary Public list of every show, ordered by name asc
 */
export const listShowsPublic = async ( options?: RequestInit): Promise<ShowPublicListItemDto[]> => {

  return customFetch<ShowPublicListItemDto[]>(getListShowsPublicUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListShowsPublicQueryKey = () => {
    return [
    `/api/shows`
    ] as const;
    }


export const getListShowsPublicQueryOptions = <TData = Awaited<ReturnType<typeof listShowsPublic>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListShowsPublicQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listShowsPublic>>> = ({ signal }) => listShowsPublic({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listShowsPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListShowsPublicQueryResult = NonNullable<Awaited<ReturnType<typeof listShowsPublic>>>
export type ListShowsPublicQueryError = unknown


export function useListShowsPublic<TData = Awaited<ReturnType<typeof listShowsPublic>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShowsPublic>>,
          TError,
          Awaited<ReturnType<typeof listShowsPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShowsPublic<TData = Awaited<ReturnType<typeof listShowsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShowsPublic>>,
          TError,
          Awaited<ReturnType<typeof listShowsPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShowsPublic<TData = Awaited<ReturnType<typeof listShowsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public list of every show, ordered by name asc
 */

export function useListShowsPublic<TData = Awaited<ReturnType<typeof listShowsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListShowsPublicQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetShowPublicUrl = (slug: string,) => {




  return `/api/shows/${slug}`
}

/**
 * @summary Public show page by slug — name/description/coverImage/theme/tags + redacted roster
 */
export const getShowPublic = async (slug: string, options?: RequestInit): Promise<ShowPublicDto> => {

  return customFetch<ShowPublicDto>(getGetShowPublicUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetShowPublicQueryKey = (slug: string,) => {
    return [
    `/api/shows/${slug}`
    ] as const;
    }


export const getGetShowPublicQueryOptions = <TData = Awaited<ReturnType<typeof getShowPublic>>, TError = unknown>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShowPublicQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShowPublic>>> = ({ signal }) => getShowPublic(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShowPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetShowPublicQueryResult = NonNullable<Awaited<ReturnType<typeof getShowPublic>>>
export type GetShowPublicQueryError = unknown


export function useGetShowPublic<TData = Awaited<ReturnType<typeof getShowPublic>>, TError = unknown>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShowPublic>>,
          TError,
          Awaited<ReturnType<typeof getShowPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShowPublic<TData = Awaited<ReturnType<typeof getShowPublic>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShowPublic>>,
          TError,
          Awaited<ReturnType<typeof getShowPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShowPublic<TData = Awaited<ReturnType<typeof getShowPublic>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public show page by slug — name/description/coverImage/theme/tags + redacted roster
 */

export function useGetShowPublic<TData = Awaited<ReturnType<typeof getShowPublic>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetShowPublicQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetShowEpisodesUrl = (slug: string,) => {




  return `/api/shows/${slug}/episodes`
}

/**
 * @summary Public upcoming/recent episodes for a show by slug
 */
export const getShowEpisodes = async (slug: string, options?: RequestInit): Promise<ShowEpisodesDto> => {

  return customFetch<ShowEpisodesDto>(getGetShowEpisodesUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetShowEpisodesQueryKey = (slug: string,) => {
    return [
    `/api/shows/${slug}/episodes`
    ] as const;
    }


export const getGetShowEpisodesQueryOptions = <TData = Awaited<ReturnType<typeof getShowEpisodes>>, TError = unknown>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowEpisodes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShowEpisodesQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShowEpisodes>>> = ({ signal }) => getShowEpisodes(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShowEpisodes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetShowEpisodesQueryResult = NonNullable<Awaited<ReturnType<typeof getShowEpisodes>>>
export type GetShowEpisodesQueryError = unknown


export function useGetShowEpisodes<TData = Awaited<ReturnType<typeof getShowEpisodes>>, TError = unknown>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowEpisodes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShowEpisodes>>,
          TError,
          Awaited<ReturnType<typeof getShowEpisodes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShowEpisodes<TData = Awaited<ReturnType<typeof getShowEpisodes>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowEpisodes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShowEpisodes>>,
          TError,
          Awaited<ReturnType<typeof getShowEpisodes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShowEpisodes<TData = Awaited<ReturnType<typeof getShowEpisodes>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowEpisodes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public upcoming/recent episodes for a show by slug
 */

export function useGetShowEpisodes<TData = Awaited<ReturnType<typeof getShowEpisodes>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShowEpisodes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetShowEpisodesQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






