/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangeRoleResultDto,
  ForceRenameResultDto,
  MeStandingDto,
  UserSearchResultDto,
  UsersControllerSearchUsersParams
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getUsersControllerGetMeUrl = () => {




  return `/api/users/me`
}

/**
 * @summary Get current user profile
 */
export const usersControllerGetMe = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getUsersControllerGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUsersControllerGetMeQueryKey = () => {
    return [
    `/api/users/me`
    ] as const;
    }


export const getUsersControllerGetMeQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetMe>>> = ({ signal }) => usersControllerGetMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetMe>>>
export type UsersControllerGetMeQueryError = unknown


export function useUsersControllerGetMe<TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetMe<TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetMe<TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user profile
 */

export function useUsersControllerGetMe<TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUsersControllerUpdateMeUrl = () => {




  return `/api/users/me`
}

/**
 * @summary Update current user profile
 */
export const usersControllerUpdateMe = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getUsersControllerUpdateMeUrl(),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getUsersControllerUpdateMeQueryKey = () => {
    return [
    'PATCH', `/api/users/me`
    ] as const;
    }


export const getUsersControllerUpdateMeQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerUpdateMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerUpdateMe>>> = ({ signal }) => usersControllerUpdateMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerUpdateMeQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerUpdateMe>>>
export type UsersControllerUpdateMeQueryError = unknown


export function useUsersControllerUpdateMe<TData = Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerUpdateMe>>,
          TError,
          Awaited<ReturnType<typeof usersControllerUpdateMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerUpdateMe<TData = Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerUpdateMe>>,
          TError,
          Awaited<ReturnType<typeof usersControllerUpdateMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerUpdateMe<TData = Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update current user profile
 */

export function useUsersControllerUpdateMe<TData = Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerUpdateMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUsersControllerGetMeStandingUrl = () => {




  return `/api/users/me/standing`
}

/**
 * @summary Get current user moderation standing
 */
export const usersControllerGetMeStanding = async ( options?: RequestInit): Promise<MeStandingDto> => {

  return customFetch<MeStandingDto>(getUsersControllerGetMeStandingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUsersControllerGetMeStandingQueryKey = () => {
    return [
    `/api/users/me/standing`
    ] as const;
    }


export const getUsersControllerGetMeStandingQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetMeStandingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetMeStanding>>> = ({ signal }) => usersControllerGetMeStanding({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetMeStandingQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetMeStanding>>>
export type UsersControllerGetMeStandingQueryError = unknown


export function useUsersControllerGetMeStanding<TData = Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMeStanding>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMeStanding>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetMeStanding<TData = Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMeStanding>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMeStanding>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetMeStanding<TData = Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user moderation standing
 */

export function useUsersControllerGetMeStanding<TData = Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMeStanding>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetMeStandingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUsersControllerRecordConsentUrl = () => {




  return `/api/users/me/consent`
}

/**
 * @summary Grant or withdraw consent for a scope (e.g. DEMOGRAPHICS)
 */
export const usersControllerRecordConsent = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getUsersControllerRecordConsentUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getUsersControllerRecordConsentQueryKey = () => {
    return [
    'POST', `/api/users/me/consent`
    ] as const;
    }


export const getUsersControllerRecordConsentQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerRecordConsentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerRecordConsent>>> = ({ signal }) => usersControllerRecordConsent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerRecordConsentQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerRecordConsent>>>
export type UsersControllerRecordConsentQueryError = unknown


export function useUsersControllerRecordConsent<TData = Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerRecordConsent>>,
          TError,
          Awaited<ReturnType<typeof usersControllerRecordConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerRecordConsent<TData = Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerRecordConsent>>,
          TError,
          Awaited<ReturnType<typeof usersControllerRecordConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerRecordConsent<TData = Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Grant or withdraw consent for a scope (e.g. DEMOGRAPHICS)
 */

export function useUsersControllerRecordConsent<TData = Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerRecordConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerRecordConsentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUsersControllerGetMyConsentUrl = () => {




  return `/api/users/me/consent`
}

/**
 * @summary Get current consent records for the authenticated user
 */
export const usersControllerGetMyConsent = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getUsersControllerGetMyConsentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUsersControllerGetMyConsentQueryKey = () => {
    return [
    `/api/users/me/consent`
    ] as const;
    }


export const getUsersControllerGetMyConsentQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetMyConsentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetMyConsent>>> = ({ signal }) => usersControllerGetMyConsent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetMyConsentQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetMyConsent>>>
export type UsersControllerGetMyConsentQueryError = unknown


export function useUsersControllerGetMyConsent<TData = Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMyConsent>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMyConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetMyConsent<TData = Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMyConsent>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMyConsent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetMyConsent<TData = Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current consent records for the authenticated user
 */

export function useUsersControllerGetMyConsent<TData = Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMyConsent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetMyConsentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUsersControllerSearchUsersUrl = (params?: UsersControllerSearchUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/users?${stringifiedParams}` : `/api/users`
}

/**
 * @summary Search/paginate users by handle/email/name and class (moderator)
 */
export const usersControllerSearchUsers = async (params?: UsersControllerSearchUsersParams, options?: RequestInit): Promise<UserSearchResultDto> => {

  return customFetch<UserSearchResultDto>(getUsersControllerSearchUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUsersControllerSearchUsersQueryKey = (params?: UsersControllerSearchUsersParams,) => {
    return [
    `/api/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getUsersControllerSearchUsersQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError = unknown>(params?: UsersControllerSearchUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerSearchUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerSearchUsers>>> = ({ signal }) => usersControllerSearchUsers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerSearchUsersQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerSearchUsers>>>
export type UsersControllerSearchUsersQueryError = unknown


export function useUsersControllerSearchUsers<TData = Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError = unknown>(
 params: undefined |  UsersControllerSearchUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerSearchUsers>>,
          TError,
          Awaited<ReturnType<typeof usersControllerSearchUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerSearchUsers<TData = Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError = unknown>(
 params?: UsersControllerSearchUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerSearchUsers>>,
          TError,
          Awaited<ReturnType<typeof usersControllerSearchUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerSearchUsers<TData = Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError = unknown>(
 params?: UsersControllerSearchUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search/paginate users by handle/email/name and class (moderator)
 */

export function useUsersControllerSearchUsers<TData = Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError = unknown>(
 params?: UsersControllerSearchUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerSearchUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerSearchUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUsersControllerForceRenameUrl = (id: string,) => {




  return `/api/users/${id}/force-rename`
}

/**
 * @summary Force-rename a user handle (moderator); audited
 */
export const usersControllerForceRename = async (id: string, options?: RequestInit): Promise<ForceRenameResultDto> => {

  return customFetch<ForceRenameResultDto>(getUsersControllerForceRenameUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getUsersControllerForceRenameQueryKey = (id: string,) => {
    return [
    'POST', `/api/users/${id}/force-rename`
    ] as const;
    }


export const getUsersControllerForceRenameQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerForceRename>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerForceRename>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerForceRenameQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerForceRename>>> = ({ signal }) => usersControllerForceRename(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerForceRename>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerForceRenameQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerForceRename>>>
export type UsersControllerForceRenameQueryError = unknown


export function useUsersControllerForceRename<TData = Awaited<ReturnType<typeof usersControllerForceRename>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerForceRename>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerForceRename>>,
          TError,
          Awaited<ReturnType<typeof usersControllerForceRename>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerForceRename<TData = Awaited<ReturnType<typeof usersControllerForceRename>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerForceRename>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerForceRename>>,
          TError,
          Awaited<ReturnType<typeof usersControllerForceRename>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerForceRename<TData = Awaited<ReturnType<typeof usersControllerForceRename>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerForceRename>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Force-rename a user handle (moderator); audited
 */

export function useUsersControllerForceRename<TData = Awaited<ReturnType<typeof usersControllerForceRename>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerForceRename>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerForceRenameQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUsersControllerChangeRoleUrl = (id: string,) => {




  return `/api/users/${id}/role`
}

/**
 * @summary Change a user role (custodian only); audited
 */
export const usersControllerChangeRole = async (id: string, options?: RequestInit): Promise<ChangeRoleResultDto> => {

  return customFetch<ChangeRoleResultDto>(getUsersControllerChangeRoleUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getUsersControllerChangeRoleQueryKey = (id: string,) => {
    return [
    'PATCH', `/api/users/${id}/role`
    ] as const;
    }


export const getUsersControllerChangeRoleQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerChangeRole>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerChangeRole>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerChangeRoleQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerChangeRole>>> = ({ signal }) => usersControllerChangeRole(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerChangeRole>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerChangeRoleQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerChangeRole>>>
export type UsersControllerChangeRoleQueryError = unknown


export function useUsersControllerChangeRole<TData = Awaited<ReturnType<typeof usersControllerChangeRole>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerChangeRole>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerChangeRole>>,
          TError,
          Awaited<ReturnType<typeof usersControllerChangeRole>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerChangeRole<TData = Awaited<ReturnType<typeof usersControllerChangeRole>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerChangeRole>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerChangeRole>>,
          TError,
          Awaited<ReturnType<typeof usersControllerChangeRole>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerChangeRole<TData = Awaited<ReturnType<typeof usersControllerChangeRole>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerChangeRole>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Change a user role (custodian only); audited
 */

export function useUsersControllerChangeRole<TData = Awaited<ReturnType<typeof usersControllerChangeRole>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerChangeRole>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerChangeRoleQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






