/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getAnalyticsControllerRecordAgeBucketUrl = () => {




  return `/api/analytics/age-bucket`
}

/**
 * @summary Record anonymous age-bucket contribution (L33/L27; PII-safe aggregate counter)
 */
export const analyticsControllerRecordAgeBucket = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getAnalyticsControllerRecordAgeBucketUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAnalyticsControllerRecordAgeBucketQueryKey = () => {
    return [
    'POST', `/api/analytics/age-bucket`
    ] as const;
    }


export const getAnalyticsControllerRecordAgeBucketQueryOptions = <TData = Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAnalyticsControllerRecordAgeBucketQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>> = ({ signal }) => analyticsControllerRecordAgeBucket({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AnalyticsControllerRecordAgeBucketQueryResult = NonNullable<Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>>
export type AnalyticsControllerRecordAgeBucketQueryError = unknown


export function useAnalyticsControllerRecordAgeBucket<TData = Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>,
          TError,
          Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAnalyticsControllerRecordAgeBucket<TData = Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>,
          TError,
          Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAnalyticsControllerRecordAgeBucket<TData = Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Record anonymous age-bucket contribution (L33/L27; PII-safe aggregate counter)
 */

export function useAnalyticsControllerRecordAgeBucket<TData = Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsControllerRecordAgeBucket>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAnalyticsControllerRecordAgeBucketQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






