/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MusicAttributionDto,
  MusicSourceDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetMusicAttributionUrl = () => {




  return `/api/music-sources/attribution`
}

/**
 * @summary Public CC-BY credits — never exposes internal clearance evidence
 */
export const getMusicAttribution = async ( options?: RequestInit): Promise<MusicAttributionDto[]> => {

  return customFetch<MusicAttributionDto[]>(getGetMusicAttributionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMusicAttributionQueryKey = () => {
    return [
    `/api/music-sources/attribution`
    ] as const;
    }


export const getGetMusicAttributionQueryOptions = <TData = Awaited<ReturnType<typeof getMusicAttribution>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMusicAttribution>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMusicAttributionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMusicAttribution>>> = ({ signal }) => getMusicAttribution({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMusicAttribution>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMusicAttributionQueryResult = NonNullable<Awaited<ReturnType<typeof getMusicAttribution>>>
export type GetMusicAttributionQueryError = unknown


export function useGetMusicAttribution<TData = Awaited<ReturnType<typeof getMusicAttribution>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMusicAttribution>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMusicAttribution>>,
          TError,
          Awaited<ReturnType<typeof getMusicAttribution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMusicAttribution<TData = Awaited<ReturnType<typeof getMusicAttribution>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMusicAttribution>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMusicAttribution>>,
          TError,
          Awaited<ReturnType<typeof getMusicAttribution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMusicAttribution<TData = Awaited<ReturnType<typeof getMusicAttribution>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMusicAttribution>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public CC-BY credits — never exposes internal clearance evidence
 */

export function useGetMusicAttribution<TData = Awaited<ReturnType<typeof getMusicAttribution>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMusicAttribution>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMusicAttributionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getListMusicSourcesUrl = () => {




  return `/api/music-sources`
}

/**
 * @summary The clean-source registry
 */
export const listMusicSources = async ( options?: RequestInit): Promise<MusicSourceDto[]> => {

  return customFetch<MusicSourceDto[]>(getListMusicSourcesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMusicSourcesQueryKey = () => {
    return [
    `/api/music-sources`
    ] as const;
    }


export const getListMusicSourcesQueryOptions = <TData = Awaited<ReturnType<typeof listMusicSources>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMusicSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMusicSourcesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMusicSources>>> = ({ signal }) => listMusicSources({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMusicSources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMusicSourcesQueryResult = NonNullable<Awaited<ReturnType<typeof listMusicSources>>>
export type ListMusicSourcesQueryError = unknown


export function useListMusicSources<TData = Awaited<ReturnType<typeof listMusicSources>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMusicSources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMusicSources>>,
          TError,
          Awaited<ReturnType<typeof listMusicSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMusicSources<TData = Awaited<ReturnType<typeof listMusicSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMusicSources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMusicSources>>,
          TError,
          Awaited<ReturnType<typeof listMusicSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMusicSources<TData = Awaited<ReturnType<typeof listMusicSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMusicSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The clean-source registry
 */

export function useListMusicSources<TData = Awaited<ReturnType<typeof listMusicSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMusicSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMusicSourcesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateMusicSourceUrl = () => {




  return `/api/music-sources`
}

/**
 * @summary Register a clean source
 */
export const createMusicSource = async ( options?: RequestInit): Promise<MusicSourceDto> => {

  return customFetch<MusicSourceDto>(getCreateMusicSourceUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCreateMusicSourceQueryKey = () => {
    return [
    'POST', `/api/music-sources`
    ] as const;
    }


export const getCreateMusicSourceQueryOptions = <TData = Awaited<ReturnType<typeof createMusicSource>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateMusicSourceQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createMusicSource>>> = ({ signal }) => createMusicSource({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createMusicSource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateMusicSourceQueryResult = NonNullable<Awaited<ReturnType<typeof createMusicSource>>>
export type CreateMusicSourceQueryError = unknown


export function useCreateMusicSource<TData = Awaited<ReturnType<typeof createMusicSource>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createMusicSource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createMusicSource>>,
          TError,
          Awaited<ReturnType<typeof createMusicSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateMusicSource<TData = Awaited<ReturnType<typeof createMusicSource>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createMusicSource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createMusicSource>>,
          TError,
          Awaited<ReturnType<typeof createMusicSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateMusicSource<TData = Awaited<ReturnType<typeof createMusicSource>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Register a clean source
 */

export function useCreateMusicSource<TData = Awaited<ReturnType<typeof createMusicSource>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateMusicSourceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateMusicSourceUrl = (id: string,) => {




  return `/api/music-sources/${id}`
}

/**
 * @summary Amend a registry entry
 */
export const updateMusicSource = async (id: string, options?: RequestInit): Promise<MusicSourceDto> => {

  return customFetch<MusicSourceDto>(getUpdateMusicSourceUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getUpdateMusicSourceQueryKey = (id: string,) => {
    return [
    'PATCH', `/api/music-sources/${id}`
    ] as const;
    }


export const getUpdateMusicSourceQueryOptions = <TData = Awaited<ReturnType<typeof updateMusicSource>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateMusicSourceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateMusicSource>>> = ({ signal }) => updateMusicSource(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateMusicSource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateMusicSourceQueryResult = NonNullable<Awaited<ReturnType<typeof updateMusicSource>>>
export type UpdateMusicSourceQueryError = unknown


export function useUpdateMusicSource<TData = Awaited<ReturnType<typeof updateMusicSource>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMusicSource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateMusicSource>>,
          TError,
          Awaited<ReturnType<typeof updateMusicSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateMusicSource<TData = Awaited<ReturnType<typeof updateMusicSource>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMusicSource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateMusicSource>>,
          TError,
          Awaited<ReturnType<typeof updateMusicSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateMusicSource<TData = Awaited<ReturnType<typeof updateMusicSource>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Amend a registry entry
 */

export function useUpdateMusicSource<TData = Awaited<ReturnType<typeof updateMusicSource>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateMusicSourceQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getDeleteMusicSourceUrl = (id: string,) => {




  return `/api/music-sources/${id}`
}

/**
 * @summary Remove a registry entry
 */
export const deleteMusicSource = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteMusicSourceUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteMusicSourceQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/music-sources/${id}`
    ] as const;
    }


export const getDeleteMusicSourceQueryOptions = <TData = Awaited<ReturnType<typeof deleteMusicSource>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteMusicSourceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteMusicSource>>> = ({ signal }) => deleteMusicSource(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteMusicSource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteMusicSourceQueryResult = NonNullable<Awaited<ReturnType<typeof deleteMusicSource>>>
export type DeleteMusicSourceQueryError = unknown


export function useDeleteMusicSource<TData = Awaited<ReturnType<typeof deleteMusicSource>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMusicSource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteMusicSource>>,
          TError,
          Awaited<ReturnType<typeof deleteMusicSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteMusicSource<TData = Awaited<ReturnType<typeof deleteMusicSource>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMusicSource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteMusicSource>>,
          TError,
          Awaited<ReturnType<typeof deleteMusicSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteMusicSource<TData = Awaited<ReturnType<typeof deleteMusicSource>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Remove a registry entry
 */

export function useDeleteMusicSource<TData = Awaited<ReturnType<typeof deleteMusicSource>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMusicSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteMusicSourceQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






