/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChartPublicDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getChartsPublicControllerGetCurrentUrl = () => {




  return `/api/charts/current`
}

/**
 * @summary Latest weekly "Most Requested" chart — empty-state safe (200, entries: []) when none exists yet
 */
export const chartsPublicControllerGetCurrent = async ( options?: RequestInit): Promise<ChartPublicDto> => {

  return customFetch<ChartPublicDto>(getChartsPublicControllerGetCurrentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getChartsPublicControllerGetCurrentQueryKey = () => {
    return [
    `/api/charts/current`
    ] as const;
    }


export const getChartsPublicControllerGetCurrentQueryOptions = <TData = Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChartsPublicControllerGetCurrentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>> = ({ signal }) => chartsPublicControllerGetCurrent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChartsPublicControllerGetCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>>
export type ChartsPublicControllerGetCurrentQueryError = unknown


export function useChartsPublicControllerGetCurrent<TData = Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>,
          TError,
          Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChartsPublicControllerGetCurrent<TData = Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>,
          TError,
          Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChartsPublicControllerGetCurrent<TData = Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Latest weekly "Most Requested" chart — empty-state safe (200, entries: []) when none exists yet
 */

export function useChartsPublicControllerGetCurrent<TData = Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chartsPublicControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChartsPublicControllerGetCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






