/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppealDto,
  BroadcastActivityPageDto,
  FilterEntryDto,
  ModerationActionResultDto,
  ModerationControllerGetAuditParams,
  ModerationControllerGetBroadcastLogsParams,
  QueueDto,
  ReinstatementRequestDto,
  ReportDto,
  StaffAuditPageDto,
  StandingDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getModerationControllerStrikeUrl = (id: string,) => {




  return `/api/mod/users/${id}/strike`
}

/**
 * @summary Issue a strike against a user; system computes the consequence
 */
export const moderationControllerStrike = async (id: string, options?: RequestInit): Promise<StandingDto> => {

  return customFetch<StandingDto>(getModerationControllerStrikeUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerStrikeQueryKey = (id: string,) => {
    return [
    'POST', `/api/mod/users/${id}/strike`
    ] as const;
    }


export const getModerationControllerStrikeQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerStrike>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerStrike>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerStrikeQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerStrike>>> = ({ signal }) => moderationControllerStrike(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerStrike>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerStrikeQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerStrike>>>
export type ModerationControllerStrikeQueryError = unknown


export function useModerationControllerStrike<TData = Awaited<ReturnType<typeof moderationControllerStrike>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerStrike>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerStrike>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerStrike>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerStrike<TData = Awaited<ReturnType<typeof moderationControllerStrike>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerStrike>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerStrike>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerStrike>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerStrike<TData = Awaited<ReturnType<typeof moderationControllerStrike>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerStrike>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Issue a strike against a user; system computes the consequence
 */

export function useModerationControllerStrike<TData = Awaited<ReturnType<typeof moderationControllerStrike>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerStrike>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerStrikeQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerActionUrl = (id: string,) => {




  return `/api/mod/users/${id}/action`
}

/**
 * @summary Direct moderator action (DELETE/WARN/MUTE/BAN/SEVERITY_OVERRIDE)
 */
export const moderationControllerAction = async (id: string, options?: RequestInit): Promise<ModerationActionResultDto> => {

  return customFetch<ModerationActionResultDto>(getModerationControllerActionUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerActionQueryKey = (id: string,) => {
    return [
    'POST', `/api/mod/users/${id}/action`
    ] as const;
    }


export const getModerationControllerActionQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerAction>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAction>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerActionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerAction>>> = ({ signal }) => moderationControllerAction(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAction>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerActionQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerAction>>>
export type ModerationControllerActionQueryError = unknown


export function useModerationControllerAction<TData = Awaited<ReturnType<typeof moderationControllerAction>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAction>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerAction>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerAction>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerAction<TData = Awaited<ReturnType<typeof moderationControllerAction>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAction>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerAction>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerAction>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerAction<TData = Awaited<ReturnType<typeof moderationControllerAction>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAction>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Direct moderator action (DELETE/WARN/MUTE/BAN/SEVERITY_OVERRIDE)
 */

export function useModerationControllerAction<TData = Awaited<ReturnType<typeof moderationControllerAction>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAction>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerActionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerListFilterUrl = () => {




  return `/api/mod/filter`
}

/**
 * @summary List all filter entries
 */
export const moderationControllerListFilter = async ( options?: RequestInit): Promise<FilterEntryDto[]> => {

  return customFetch<FilterEntryDto[]>(getModerationControllerListFilterUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getModerationControllerListFilterQueryKey = () => {
    return [
    `/api/mod/filter`
    ] as const;
    }


export const getModerationControllerListFilterQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerListFilter>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerListFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerListFilterQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerListFilter>>> = ({ signal }) => moderationControllerListFilter({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerListFilter>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerListFilterQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerListFilter>>>
export type ModerationControllerListFilterQueryError = unknown


export function useModerationControllerListFilter<TData = Awaited<ReturnType<typeof moderationControllerListFilter>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerListFilter>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerListFilter>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerListFilter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerListFilter<TData = Awaited<ReturnType<typeof moderationControllerListFilter>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerListFilter>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerListFilter>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerListFilter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerListFilter<TData = Awaited<ReturnType<typeof moderationControllerListFilter>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerListFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all filter entries
 */

export function useModerationControllerListFilter<TData = Awaited<ReturnType<typeof moderationControllerListFilter>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerListFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerListFilterQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerAddFilterUrl = () => {




  return `/api/mod/filter`
}

/**
 * @summary Add a word/phrase to the content filter (stored normalized)
 */
export const moderationControllerAddFilter = async ( options?: RequestInit): Promise<FilterEntryDto> => {

  return customFetch<FilterEntryDto>(getModerationControllerAddFilterUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerAddFilterQueryKey = () => {
    return [
    'POST', `/api/mod/filter`
    ] as const;
    }


export const getModerationControllerAddFilterQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerAddFilterQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerAddFilter>>> = ({ signal }) => moderationControllerAddFilter({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerAddFilterQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerAddFilter>>>
export type ModerationControllerAddFilterQueryError = unknown


export function useModerationControllerAddFilter<TData = Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerAddFilter>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerAddFilter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerAddFilter<TData = Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerAddFilter>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerAddFilter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerAddFilter<TData = Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Add a word/phrase to the content filter (stored normalized)
 */

export function useModerationControllerAddFilter<TData = Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerAddFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerAddFilterQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerRemoveFilterUrl = (id: string,) => {




  return `/api/mod/filter/${id}`
}

/**
 * @summary Remove a filter entry
 */
export const moderationControllerRemoveFilter = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getModerationControllerRemoveFilterUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getModerationControllerRemoveFilterQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/mod/filter/${id}`
    ] as const;
    }


export const getModerationControllerRemoveFilterQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerRemoveFilterQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerRemoveFilter>>> = ({ signal }) => moderationControllerRemoveFilter(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerRemoveFilterQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerRemoveFilter>>>
export type ModerationControllerRemoveFilterQueryError = unknown


export function useModerationControllerRemoveFilter<TData = Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerRemoveFilter>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerRemoveFilter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerRemoveFilter<TData = Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerRemoveFilter>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerRemoveFilter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerRemoveFilter<TData = Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Remove a filter entry
 */

export function useModerationControllerRemoveFilter<TData = Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerRemoveFilter>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerRemoveFilterQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerCreateReportUrl = () => {




  return `/api/mod/reports`
}

/**
 * @summary File a report against a user or message (any authenticated user)
 */
export const moderationControllerCreateReport = async ( options?: RequestInit): Promise<ReportDto> => {

  return customFetch<ReportDto>(getModerationControllerCreateReportUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerCreateReportQueryKey = () => {
    return [
    'POST', `/api/mod/reports`
    ] as const;
    }


export const getModerationControllerCreateReportQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerCreateReportQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerCreateReport>>> = ({ signal }) => moderationControllerCreateReport({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerCreateReportQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerCreateReport>>>
export type ModerationControllerCreateReportQueryError = unknown


export function useModerationControllerCreateReport<TData = Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerCreateReport>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerCreateReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerCreateReport<TData = Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerCreateReport>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerCreateReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerCreateReport<TData = Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary File a report against a user or message (any authenticated user)
 */

export function useModerationControllerCreateReport<TData = Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerCreateReportQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerGetQueueUrl = () => {




  return `/api/mod/queue`
}

/**
 * @summary Unified mod queue: open reports, watch-flags, appeals, and reinstatement requests
 */
export const moderationControllerGetQueue = async ( options?: RequestInit): Promise<QueueDto> => {

  return customFetch<QueueDto>(getModerationControllerGetQueueUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getModerationControllerGetQueueQueryKey = () => {
    return [
    `/api/mod/queue`
    ] as const;
    }


export const getModerationControllerGetQueueQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerGetQueueQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerGetQueue>>> = ({ signal }) => moderationControllerGetQueue({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerGetQueueQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerGetQueue>>>
export type ModerationControllerGetQueueQueryError = unknown


export function useModerationControllerGetQueue<TData = Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerGetQueue>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerGetQueue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerGetQueue<TData = Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerGetQueue>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerGetQueue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerGetQueue<TData = Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Unified mod queue: open reports, watch-flags, appeals, and reinstatement requests
 */

export function useModerationControllerGetQueue<TData = Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetQueue>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerGetQueueQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerResolveReportUrl = (id: string,) => {




  return `/api/mod/reports/${id}/resolve`
}

/**
 * @summary Resolve a report: ACTIONED/DISMISSED, with a required written reason
 */
export const moderationControllerResolveReport = async (id: string, options?: RequestInit): Promise<ReportDto> => {

  return customFetch<ReportDto>(getModerationControllerResolveReportUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerResolveReportQueryKey = (id: string,) => {
    return [
    'POST', `/api/mod/reports/${id}/resolve`
    ] as const;
    }


export const getModerationControllerResolveReportQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerResolveReportQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerResolveReport>>> = ({ signal }) => moderationControllerResolveReport(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerResolveReportQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerResolveReport>>>
export type ModerationControllerResolveReportQueryError = unknown


export function useModerationControllerResolveReport<TData = Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerResolveReport>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerResolveReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerResolveReport<TData = Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerResolveReport>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerResolveReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerResolveReport<TData = Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve a report: ACTIONED/DISMISSED, with a required written reason
 */

export function useModerationControllerResolveReport<TData = Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerResolveReportQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerGetAuditUrl = (params?: ModerationControllerGetAuditParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/mod/audit?${stringifiedParams}` : `/api/mod/audit`
}

/**
 * @summary Paginated, filterable read of the staff audit log
 */
export const moderationControllerGetAudit = async (params?: ModerationControllerGetAuditParams, options?: RequestInit): Promise<StaffAuditPageDto> => {

  return customFetch<StaffAuditPageDto>(getModerationControllerGetAuditUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getModerationControllerGetAuditQueryKey = (params?: ModerationControllerGetAuditParams,) => {
    return [
    `/api/mod/audit`, ...(params ? [params] : [])
    ] as const;
    }


export const getModerationControllerGetAuditQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError = unknown>(params?: ModerationControllerGetAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerGetAuditQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerGetAudit>>> = ({ signal }) => moderationControllerGetAudit(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerGetAuditQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerGetAudit>>>
export type ModerationControllerGetAuditQueryError = unknown


export function useModerationControllerGetAudit<TData = Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError = unknown>(
 params: undefined |  ModerationControllerGetAuditParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerGetAudit>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerGetAudit>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerGetAudit<TData = Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError = unknown>(
 params?: ModerationControllerGetAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerGetAudit>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerGetAudit>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerGetAudit<TData = Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError = unknown>(
 params?: ModerationControllerGetAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paginated, filterable read of the staff audit log
 */

export function useModerationControllerGetAudit<TData = Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError = unknown>(
 params?: ModerationControllerGetAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetAudit>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerGetAuditQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerGetBroadcastLogsUrl = (params?: ModerationControllerGetBroadcastLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/mod/logs/broadcast?${stringifiedParams}` : `/api/mod/logs/broadcast`
}

/**
 * @summary Paginated, filterable read of the broadcast activity log
 */
export const moderationControllerGetBroadcastLogs = async (params?: ModerationControllerGetBroadcastLogsParams, options?: RequestInit): Promise<BroadcastActivityPageDto> => {

  return customFetch<BroadcastActivityPageDto>(getModerationControllerGetBroadcastLogsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getModerationControllerGetBroadcastLogsQueryKey = (params?: ModerationControllerGetBroadcastLogsParams,) => {
    return [
    `/api/mod/logs/broadcast`, ...(params ? [params] : [])
    ] as const;
    }


export const getModerationControllerGetBroadcastLogsQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError = unknown>(params?: ModerationControllerGetBroadcastLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerGetBroadcastLogsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>> = ({ signal }) => moderationControllerGetBroadcastLogs(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerGetBroadcastLogsQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>>
export type ModerationControllerGetBroadcastLogsQueryError = unknown


export function useModerationControllerGetBroadcastLogs<TData = Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError = unknown>(
 params: undefined |  ModerationControllerGetBroadcastLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerGetBroadcastLogs<TData = Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError = unknown>(
 params?: ModerationControllerGetBroadcastLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerGetBroadcastLogs<TData = Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError = unknown>(
 params?: ModerationControllerGetBroadcastLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paginated, filterable read of the broadcast activity log
 */

export function useModerationControllerGetBroadcastLogs<TData = Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError = unknown>(
 params?: ModerationControllerGetBroadcastLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerGetBroadcastLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerGetBroadcastLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerCreateAppealUrl = () => {




  return `/api/mod/appeals`
}

/**
 * @summary File an appeal against a strike or standing (any authenticated user)
 */
export const moderationControllerCreateAppeal = async ( options?: RequestInit): Promise<AppealDto> => {

  return customFetch<AppealDto>(getModerationControllerCreateAppealUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerCreateAppealQueryKey = () => {
    return [
    'POST', `/api/mod/appeals`
    ] as const;
    }


export const getModerationControllerCreateAppealQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerCreateAppealQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerCreateAppeal>>> = ({ signal }) => moderationControllerCreateAppeal({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerCreateAppealQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerCreateAppeal>>>
export type ModerationControllerCreateAppealQueryError = unknown


export function useModerationControllerCreateAppeal<TData = Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerCreateAppeal>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerCreateAppeal>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerCreateAppeal<TData = Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerCreateAppeal>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerCreateAppeal>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerCreateAppeal<TData = Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary File an appeal against a strike or standing (any authenticated user)
 */

export function useModerationControllerCreateAppeal<TData = Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateAppeal>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerCreateAppealQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerResolveAppealUrl = (id: string,) => {




  return `/api/mod/appeals/${id}/resolve`
}

/**
 * @summary Resolve an appeal: UPHELD/REDUCED/OVERTURNED, with a required written response
 */
export const moderationControllerResolveAppeal = async (id: string, options?: RequestInit): Promise<AppealDto> => {

  return customFetch<AppealDto>(getModerationControllerResolveAppealUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerResolveAppealQueryKey = (id: string,) => {
    return [
    'POST', `/api/mod/appeals/${id}/resolve`
    ] as const;
    }


export const getModerationControllerResolveAppealQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerResolveAppealQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerResolveAppeal>>> = ({ signal }) => moderationControllerResolveAppeal(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerResolveAppealQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerResolveAppeal>>>
export type ModerationControllerResolveAppealQueryError = unknown


export function useModerationControllerResolveAppeal<TData = Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerResolveAppeal>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerResolveAppeal>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerResolveAppeal<TData = Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerResolveAppeal>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerResolveAppeal>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerResolveAppeal<TData = Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve an appeal: UPHELD/REDUCED/OVERTURNED, with a required written response
 */

export function useModerationControllerResolveAppeal<TData = Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerResolveAppeal>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerResolveAppealQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerCreateReinstatementUrl = () => {




  return `/api/mod/reinstatement`
}

/**
 * @summary Request reinstatement (any currently banned, authenticated user)
 */
export const moderationControllerCreateReinstatement = async ( options?: RequestInit): Promise<ReinstatementRequestDto> => {

  return customFetch<ReinstatementRequestDto>(getModerationControllerCreateReinstatementUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerCreateReinstatementQueryKey = () => {
    return [
    'POST', `/api/mod/reinstatement`
    ] as const;
    }


export const getModerationControllerCreateReinstatementQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerCreateReinstatementQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>> = ({ signal }) => moderationControllerCreateReinstatement({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerCreateReinstatementQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>>
export type ModerationControllerCreateReinstatementQueryError = unknown


export function useModerationControllerCreateReinstatement<TData = Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerCreateReinstatement<TData = Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerCreateReinstatement<TData = Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Request reinstatement (any currently banned, authenticated user)
 */

export function useModerationControllerCreateReinstatement<TData = Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerCreateReinstatement>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerCreateReinstatementQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getModerationControllerApproveReinstatementUrl = (id: string,) => {




  return `/api/mod/reinstatement/${id}/approve`
}

/**
 * @summary Approve or deny a reinstatement request (custodian only)
 */
export const moderationControllerApproveReinstatement = async (id: string, options?: RequestInit): Promise<ReinstatementRequestDto> => {

  return customFetch<ReinstatementRequestDto>(getModerationControllerApproveReinstatementUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getModerationControllerApproveReinstatementQueryKey = (id: string,) => {
    return [
    'POST', `/api/mod/reinstatement/${id}/approve`
    ] as const;
    }


export const getModerationControllerApproveReinstatementQueryOptions = <TData = Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getModerationControllerApproveReinstatementQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>> = ({ signal }) => moderationControllerApproveReinstatement(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ModerationControllerApproveReinstatementQueryResult = NonNullable<Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>>
export type ModerationControllerApproveReinstatementQueryError = unknown


export function useModerationControllerApproveReinstatement<TData = Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerApproveReinstatement<TData = Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>,
          TError,
          Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useModerationControllerApproveReinstatement<TData = Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Approve or deny a reinstatement request (custodian only)
 */

export function useModerationControllerApproveReinstatement<TData = Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof moderationControllerApproveReinstatement>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getModerationControllerApproveReinstatementQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






