/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DjPublicDto,
  DjPublicListItemDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListDjsPublicUrl = () => {




  return `/api/djs`
}

/**
 * @summary Public list of active DJs, ordered by displayName asc
 */
export const listDjsPublic = async ( options?: RequestInit): Promise<DjPublicListItemDto[]> => {

  return customFetch<DjPublicListItemDto[]>(getListDjsPublicUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDjsPublicQueryKey = () => {
    return [
    `/api/djs`
    ] as const;
    }


export const getListDjsPublicQueryOptions = <TData = Awaited<ReturnType<typeof listDjsPublic>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDjsPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDjsPublicQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDjsPublic>>> = ({ signal }) => listDjsPublic({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDjsPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDjsPublicQueryResult = NonNullable<Awaited<ReturnType<typeof listDjsPublic>>>
export type ListDjsPublicQueryError = unknown


export function useListDjsPublic<TData = Awaited<ReturnType<typeof listDjsPublic>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDjsPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDjsPublic>>,
          TError,
          Awaited<ReturnType<typeof listDjsPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDjsPublic<TData = Awaited<ReturnType<typeof listDjsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDjsPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDjsPublic>>,
          TError,
          Awaited<ReturnType<typeof listDjsPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDjsPublic<TData = Awaited<ReturnType<typeof listDjsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDjsPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public list of active DJs, ordered by displayName asc
 */

export function useListDjsPublic<TData = Awaited<ReturnType<typeof listDjsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDjsPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDjsPublicQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetDjPublicUrl = (id: string,) => {




  return `/api/djs/${id}`
}

/**
 * @summary Public DJ profile from RosterEntry — displayName/photoUrl/bio/activeShows, never linkedAccountId
 */
export const getDjPublic = async (id: string, options?: RequestInit): Promise<DjPublicDto> => {

  return customFetch<DjPublicDto>(getGetDjPublicUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDjPublicQueryKey = (id: string,) => {
    return [
    `/api/djs/${id}`
    ] as const;
    }


export const getGetDjPublicQueryOptions = <TData = Awaited<ReturnType<typeof getDjPublic>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDjPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDjPublicQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDjPublic>>> = ({ signal }) => getDjPublic(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDjPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDjPublicQueryResult = NonNullable<Awaited<ReturnType<typeof getDjPublic>>>
export type GetDjPublicQueryError = unknown


export function useGetDjPublic<TData = Awaited<ReturnType<typeof getDjPublic>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDjPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDjPublic>>,
          TError,
          Awaited<ReturnType<typeof getDjPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDjPublic<TData = Awaited<ReturnType<typeof getDjPublic>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDjPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDjPublic>>,
          TError,
          Awaited<ReturnType<typeof getDjPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDjPublic<TData = Awaited<ReturnType<typeof getDjPublic>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDjPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public DJ profile from RosterEntry — displayName/photoUrl/bio/activeShows, never linkedAccountId
 */

export function useGetDjPublic<TData = Awaited<ReturnType<typeof getDjPublic>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDjPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDjPublicQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






