/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListShowOccurrencesParams,
  ShowDto,
  ShowOccurrenceAdminDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListShowsAdminUrl = () => {




  return `/api/shows/admin`
}

/**
 * @summary Staff list of shows with roster and cadence (moderator)
 */
export const listShowsAdmin = async ( options?: RequestInit): Promise<ShowDto[]> => {

  return customFetch<ShowDto[]>(getListShowsAdminUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListShowsAdminQueryKey = () => {
    return [
    `/api/shows/admin`
    ] as const;
    }


export const getListShowsAdminQueryOptions = <TData = Awaited<ReturnType<typeof listShowsAdmin>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsAdmin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListShowsAdminQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listShowsAdmin>>> = ({ signal }) => listShowsAdmin({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listShowsAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListShowsAdminQueryResult = NonNullable<Awaited<ReturnType<typeof listShowsAdmin>>>
export type ListShowsAdminQueryError = unknown


export function useListShowsAdmin<TData = Awaited<ReturnType<typeof listShowsAdmin>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShowsAdmin>>,
          TError,
          Awaited<ReturnType<typeof listShowsAdmin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShowsAdmin<TData = Awaited<ReturnType<typeof listShowsAdmin>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShowsAdmin>>,
          TError,
          Awaited<ReturnType<typeof listShowsAdmin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShowsAdmin<TData = Awaited<ReturnType<typeof listShowsAdmin>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsAdmin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Staff list of shows with roster and cadence (moderator)
 */

export function useListShowsAdmin<TData = Awaited<ReturnType<typeof listShowsAdmin>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowsAdmin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListShowsAdminQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getShowsControllerCreateUrl = () => {




  return `/api/shows`
}

/**
 * @summary Create a show
 */
export const showsControllerCreate = async ( options?: RequestInit): Promise<ShowDto> => {

  return customFetch<ShowDto>(getShowsControllerCreateUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getShowsControllerCreateQueryKey = () => {
    return [
    'POST', `/api/shows`
    ] as const;
    }


export const getShowsControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof showsControllerCreate>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowsControllerCreateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showsControllerCreate>>> = ({ signal }) => showsControllerCreate({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showsControllerCreate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowsControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof showsControllerCreate>>>
export type ShowsControllerCreateQueryError = unknown


export function useShowsControllerCreate<TData = Awaited<ReturnType<typeof showsControllerCreate>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerCreate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showsControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof showsControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowsControllerCreate<TData = Awaited<ReturnType<typeof showsControllerCreate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerCreate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showsControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof showsControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowsControllerCreate<TData = Awaited<ReturnType<typeof showsControllerCreate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create a show
 */

export function useShowsControllerCreate<TData = Awaited<ReturnType<typeof showsControllerCreate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowsControllerCreateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getShowsControllerUpdateUrl = (id: string,) => {




  return `/api/shows/${id}`
}

/**
 * @summary Update a show
 */
export const showsControllerUpdate = async (id: string, options?: RequestInit): Promise<ShowDto> => {

  return customFetch<ShowDto>(getShowsControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getShowsControllerUpdateQueryKey = (id: string,) => {
    return [
    'PATCH', `/api/shows/${id}`
    ] as const;
    }


export const getShowsControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof showsControllerUpdate>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowsControllerUpdateQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showsControllerUpdate>>> = ({ signal }) => showsControllerUpdate(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showsControllerUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowsControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof showsControllerUpdate>>>
export type ShowsControllerUpdateQueryError = unknown


export function useShowsControllerUpdate<TData = Awaited<ReturnType<typeof showsControllerUpdate>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showsControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof showsControllerUpdate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowsControllerUpdate<TData = Awaited<ReturnType<typeof showsControllerUpdate>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showsControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof showsControllerUpdate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowsControllerUpdate<TData = Awaited<ReturnType<typeof showsControllerUpdate>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update a show
 */

export function useShowsControllerUpdate<TData = Awaited<ReturnType<typeof showsControllerUpdate>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowsControllerUpdateQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getShowsControllerRemoveUrl = (id: string,) => {




  return `/api/shows/${id}`
}

/**
 * @summary Delete a show
 */
export const showsControllerRemove = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getShowsControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getShowsControllerRemoveQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/shows/${id}`
    ] as const;
    }


export const getShowsControllerRemoveQueryOptions = <TData = Awaited<ReturnType<typeof showsControllerRemove>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowsControllerRemoveQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showsControllerRemove>>> = ({ signal }) => showsControllerRemove(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showsControllerRemove>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowsControllerRemoveQueryResult = NonNullable<Awaited<ReturnType<typeof showsControllerRemove>>>
export type ShowsControllerRemoveQueryError = unknown


export function useShowsControllerRemove<TData = Awaited<ReturnType<typeof showsControllerRemove>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerRemove>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showsControllerRemove>>,
          TError,
          Awaited<ReturnType<typeof showsControllerRemove>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowsControllerRemove<TData = Awaited<ReturnType<typeof showsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerRemove>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showsControllerRemove>>,
          TError,
          Awaited<ReturnType<typeof showsControllerRemove>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowsControllerRemove<TData = Awaited<ReturnType<typeof showsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete a show
 */

export function useShowsControllerRemove<TData = Awaited<ReturnType<typeof showsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowsControllerRemoveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getListShowOccurrencesUrl = (params: ListShowOccurrencesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/shows/admin/occurrences?${stringifiedParams}` : `/api/shows/admin/occurrences`
}

/**
 * @summary A station date's occurrences with overrides (moderator)
 */
export const listShowOccurrences = async (params: ListShowOccurrencesParams, options?: RequestInit): Promise<ShowOccurrenceAdminDto[]> => {

  return customFetch<ShowOccurrenceAdminDto[]>(getListShowOccurrencesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListShowOccurrencesQueryKey = (params?: ListShowOccurrencesParams,) => {
    return [
    `/api/shows/admin/occurrences`, ...(params ? [params] : [])
    ] as const;
    }


export const getListShowOccurrencesQueryOptions = <TData = Awaited<ReturnType<typeof listShowOccurrences>>, TError = unknown>(params: ListShowOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowOccurrences>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListShowOccurrencesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listShowOccurrences>>> = ({ signal }) => listShowOccurrences(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listShowOccurrences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListShowOccurrencesQueryResult = NonNullable<Awaited<ReturnType<typeof listShowOccurrences>>>
export type ListShowOccurrencesQueryError = unknown


export function useListShowOccurrences<TData = Awaited<ReturnType<typeof listShowOccurrences>>, TError = unknown>(
 params: ListShowOccurrencesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowOccurrences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShowOccurrences>>,
          TError,
          Awaited<ReturnType<typeof listShowOccurrences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShowOccurrences<TData = Awaited<ReturnType<typeof listShowOccurrences>>, TError = unknown>(
 params: ListShowOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowOccurrences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShowOccurrences>>,
          TError,
          Awaited<ReturnType<typeof listShowOccurrences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShowOccurrences<TData = Awaited<ReturnType<typeof listShowOccurrences>>, TError = unknown>(
 params: ListShowOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowOccurrences>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary A station date's occurrences with overrides (moderator)
 */

export function useListShowOccurrences<TData = Awaited<ReturnType<typeof listShowOccurrences>>, TError = unknown>(
 params: ListShowOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShowOccurrences>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListShowOccurrencesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpsertShowOccurrenceUrl = (id: string,
    date: string,) => {




  return `/api/shows/${id}/occurrences/${date}`
}

/**
 * @summary Delay or cancel one occurrence (moderator, audited)
 */
export const upsertShowOccurrence = async (id: string,
    date: string, options?: RequestInit): Promise<ShowOccurrenceAdminDto> => {

  return customFetch<ShowOccurrenceAdminDto>(getUpsertShowOccurrenceUrl(id,date),
  {
    ...options,
    method: 'PUT'


  }
);}





export const getUpsertShowOccurrenceQueryKey = (id: string,
    date: string,) => {
    return [
    'PUT', `/api/shows/${id}/occurrences/${date}`
    ] as const;
    }


export const getUpsertShowOccurrenceQueryOptions = <TData = Awaited<ReturnType<typeof upsertShowOccurrence>>, TError = unknown>(id: string,
    date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertShowOccurrence>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpsertShowOccurrenceQueryKey(id,date);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof upsertShowOccurrence>>> = ({ signal }) => upsertShowOccurrence(id,date, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && date !== null && date !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof upsertShowOccurrence>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpsertShowOccurrenceQueryResult = NonNullable<Awaited<ReturnType<typeof upsertShowOccurrence>>>
export type UpsertShowOccurrenceQueryError = unknown


export function useUpsertShowOccurrence<TData = Awaited<ReturnType<typeof upsertShowOccurrence>>, TError = unknown>(
 id: string,
    date: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertShowOccurrence>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof upsertShowOccurrence>>,
          TError,
          Awaited<ReturnType<typeof upsertShowOccurrence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpsertShowOccurrence<TData = Awaited<ReturnType<typeof upsertShowOccurrence>>, TError = unknown>(
 id: string,
    date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertShowOccurrence>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof upsertShowOccurrence>>,
          TError,
          Awaited<ReturnType<typeof upsertShowOccurrence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpsertShowOccurrence<TData = Awaited<ReturnType<typeof upsertShowOccurrence>>, TError = unknown>(
 id: string,
    date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertShowOccurrence>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delay or cancel one occurrence (moderator, audited)
 */

export function useUpsertShowOccurrence<TData = Awaited<ReturnType<typeof upsertShowOccurrence>>, TError = unknown>(
 id: string,
    date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertShowOccurrence>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpsertShowOccurrenceQueryOptions(id,date,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getResumeShowOccurrenceUrl = (id: string,
    date: string,) => {




  return `/api/shows/${id}/occurrences/${date}`
}

/**
 * @summary Resume a delayed/cancelled occurrence (moderator, audited)
 */
export const resumeShowOccurrence = async (id: string,
    date: string, options?: RequestInit): Promise<ShowOccurrenceAdminDto> => {

  return customFetch<ShowOccurrenceAdminDto>(getResumeShowOccurrenceUrl(id,date),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getResumeShowOccurrenceQueryKey = (id: string,
    date: string,) => {
    return [
    'DELETE', `/api/shows/${id}/occurrences/${date}`
    ] as const;
    }


export const getResumeShowOccurrenceQueryOptions = <TData = Awaited<ReturnType<typeof resumeShowOccurrence>>, TError = unknown>(id: string,
    date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumeShowOccurrence>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResumeShowOccurrenceQueryKey(id,date);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof resumeShowOccurrence>>> = ({ signal }) => resumeShowOccurrence(id,date, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && date !== null && date !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resumeShowOccurrence>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResumeShowOccurrenceQueryResult = NonNullable<Awaited<ReturnType<typeof resumeShowOccurrence>>>
export type ResumeShowOccurrenceQueryError = unknown


export function useResumeShowOccurrence<TData = Awaited<ReturnType<typeof resumeShowOccurrence>>, TError = unknown>(
 id: string,
    date: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumeShowOccurrence>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resumeShowOccurrence>>,
          TError,
          Awaited<ReturnType<typeof resumeShowOccurrence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResumeShowOccurrence<TData = Awaited<ReturnType<typeof resumeShowOccurrence>>, TError = unknown>(
 id: string,
    date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumeShowOccurrence>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resumeShowOccurrence>>,
          TError,
          Awaited<ReturnType<typeof resumeShowOccurrence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResumeShowOccurrence<TData = Awaited<ReturnType<typeof resumeShowOccurrence>>, TError = unknown>(
 id: string,
    date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumeShowOccurrence>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resume a delayed/cancelled occurrence (moderator, audited)
 */

export function useResumeShowOccurrence<TData = Awaited<ReturnType<typeof resumeShowOccurrence>>, TError = unknown>(
 id: string,
    date: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resumeShowOccurrence>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResumeShowOccurrenceQueryOptions(id,date,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






