/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BoothChatDto,
  ChatMessageResponseDto,
  CreatePollDto,
  PinTopicDto,
  PinnedTopicResponseDto,
  PollResponseDto,
  QueueActDto,
  QueueActionResponseDto,
  StudioQueueResponseDto,
  StudioSessionClearResponseDto,
  StudioSessionResponseDto,
  StudioSessionStatusResponseDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetStudioTodayUrl = () => {




  return `/api/studio/today`
}

/**
 * @summary Get studio today view
 */
export const getStudioToday = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getGetStudioTodayUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudioTodayQueryKey = () => {
    return [
    `/api/studio/today`
    ] as const;
    }


export const getGetStudioTodayQueryOptions = <TData = Awaited<ReturnType<typeof getStudioToday>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioToday>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudioTodayQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudioToday>>> = ({ signal }) => getStudioToday({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudioToday>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudioTodayQueryResult = NonNullable<Awaited<ReturnType<typeof getStudioToday>>>
export type GetStudioTodayQueryError = unknown


export function useGetStudioToday<TData = Awaited<ReturnType<typeof getStudioToday>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioToday>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudioToday>>,
          TError,
          Awaited<ReturnType<typeof getStudioToday>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudioToday<TData = Awaited<ReturnType<typeof getStudioToday>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioToday>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudioToday>>,
          TError,
          Awaited<ReturnType<typeof getStudioToday>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudioToday<TData = Awaited<ReturnType<typeof getStudioToday>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioToday>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get studio today view
 */

export function useGetStudioToday<TData = Awaited<ReturnType<typeof getStudioToday>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioToday>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudioTodayQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getTimeInStudioUrl = () => {




  return `/api/studio/time-in`
}

/**
 * @summary DJ time-in (tap in)
 */
export const timeInStudio = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getTimeInStudioUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTimeInStudioQueryKey = () => {
    return [
    'POST', `/api/studio/time-in`
    ] as const;
    }


export const getTimeInStudioQueryOptions = <TData = Awaited<ReturnType<typeof timeInStudio>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeInStudio>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTimeInStudioQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof timeInStudio>>> = ({ signal }) => timeInStudio({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof timeInStudio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TimeInStudioQueryResult = NonNullable<Awaited<ReturnType<typeof timeInStudio>>>
export type TimeInStudioQueryError = unknown


export function useTimeInStudio<TData = Awaited<ReturnType<typeof timeInStudio>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeInStudio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof timeInStudio>>,
          TError,
          Awaited<ReturnType<typeof timeInStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTimeInStudio<TData = Awaited<ReturnType<typeof timeInStudio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeInStudio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof timeInStudio>>,
          TError,
          Awaited<ReturnType<typeof timeInStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTimeInStudio<TData = Awaited<ReturnType<typeof timeInStudio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeInStudio>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DJ time-in (tap in)
 */

export function useTimeInStudio<TData = Awaited<ReturnType<typeof timeInStudio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeInStudio>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTimeInStudioQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getTimeOutStudioUrl = () => {




  return `/api/studio/time-out`
}

/**
 * @summary DJ time-out (tap out)
 */
export const timeOutStudio = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getTimeOutStudioUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTimeOutStudioQueryKey = () => {
    return [
    'POST', `/api/studio/time-out`
    ] as const;
    }


export const getTimeOutStudioQueryOptions = <TData = Awaited<ReturnType<typeof timeOutStudio>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeOutStudio>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTimeOutStudioQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof timeOutStudio>>> = ({ signal }) => timeOutStudio({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof timeOutStudio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TimeOutStudioQueryResult = NonNullable<Awaited<ReturnType<typeof timeOutStudio>>>
export type TimeOutStudioQueryError = unknown


export function useTimeOutStudio<TData = Awaited<ReturnType<typeof timeOutStudio>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeOutStudio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof timeOutStudio>>,
          TError,
          Awaited<ReturnType<typeof timeOutStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTimeOutStudio<TData = Awaited<ReturnType<typeof timeOutStudio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeOutStudio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof timeOutStudio>>,
          TError,
          Awaited<ReturnType<typeof timeOutStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTimeOutStudio<TData = Awaited<ReturnType<typeof timeOutStudio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeOutStudio>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DJ time-out (tap out)
 */

export function useTimeOutStudio<TData = Awaited<ReturnType<typeof timeOutStudio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timeOutStudio>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTimeOutStudioQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetStudioQueueUrl = () => {




  return `/api/studio/queue`
}

/**
 * @summary Live engagement queue
 */
export const getStudioQueue = async ( options?: RequestInit): Promise<StudioQueueResponseDto> => {

  return customFetch<StudioQueueResponseDto>(getGetStudioQueueUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudioQueueQueryKey = () => {
    return [
    `/api/studio/queue`
    ] as const;
    }


export const getGetStudioQueueQueryOptions = <TData = Awaited<ReturnType<typeof getStudioQueue>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioQueue>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudioQueueQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudioQueue>>> = ({ signal }) => getStudioQueue({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudioQueue>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudioQueueQueryResult = NonNullable<Awaited<ReturnType<typeof getStudioQueue>>>
export type GetStudioQueueQueryError = unknown


export function useGetStudioQueue<TData = Awaited<ReturnType<typeof getStudioQueue>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioQueue>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudioQueue>>,
          TError,
          Awaited<ReturnType<typeof getStudioQueue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudioQueue<TData = Awaited<ReturnType<typeof getStudioQueue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioQueue>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudioQueue>>,
          TError,
          Awaited<ReturnType<typeof getStudioQueue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudioQueue<TData = Awaited<ReturnType<typeof getStudioQueue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioQueue>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Live engagement queue
 */

export function useGetStudioQueue<TData = Awaited<ReturnType<typeof getStudioQueue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudioQueue>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudioQueueQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getActOnQueueItemUrl = (id: string,) => {




  return `/api/studio/queue/${id}/act`
}

/**
 * @summary Act on a queue item
 */
export const actOnQueueItem = async (id: string,
    queueActDto: QueueActDto, options?: RequestInit): Promise<QueueActionResponseDto> => {

  return customFetch<QueueActionResponseDto>(getActOnQueueItemUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(queueActDto)
  }
);}





export const getActOnQueueItemQueryKey = (id: string,
    queueActDto?: QueueActDto,) => {
    return [
    'POST', `/api/studio/queue/${id}/act`, queueActDto
    ] as const;
    }


export const getActOnQueueItemQueryOptions = <TData = Awaited<ReturnType<typeof actOnQueueItem>>, TError = unknown>(id: string,
    queueActDto: QueueActDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actOnQueueItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActOnQueueItemQueryKey(id,queueActDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof actOnQueueItem>>> = ({ signal }) => actOnQueueItem(id,queueActDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof actOnQueueItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActOnQueueItemQueryResult = NonNullable<Awaited<ReturnType<typeof actOnQueueItem>>>
export type ActOnQueueItemQueryError = unknown


export function useActOnQueueItem<TData = Awaited<ReturnType<typeof actOnQueueItem>>, TError = unknown>(
 id: string,
    queueActDto: QueueActDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof actOnQueueItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof actOnQueueItem>>,
          TError,
          Awaited<ReturnType<typeof actOnQueueItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActOnQueueItem<TData = Awaited<ReturnType<typeof actOnQueueItem>>, TError = unknown>(
 id: string,
    queueActDto: QueueActDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actOnQueueItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof actOnQueueItem>>,
          TError,
          Awaited<ReturnType<typeof actOnQueueItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActOnQueueItem<TData = Awaited<ReturnType<typeof actOnQueueItem>>, TError = unknown>(
 id: string,
    queueActDto: QueueActDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actOnQueueItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Act on a queue item
 */

export function useActOnQueueItem<TData = Awaited<ReturnType<typeof actOnQueueItem>>, TError = unknown>(
 id: string,
    queueActDto: QueueActDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actOnQueueItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActOnQueueItemQueryOptions(id,queueActDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreatePollUrl = () => {




  return `/api/studio/polls`
}

/**
 * @summary Launch a poll
 */
export const createPoll = async (createPollDto: CreatePollDto, options?: RequestInit): Promise<PollResponseDto> => {

  return customFetch<PollResponseDto>(getCreatePollUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPollDto)
  }
);}





export const getCreatePollQueryKey = (createPollDto?: CreatePollDto,) => {
    return [
    'POST', `/api/studio/polls`, createPollDto
    ] as const;
    }


export const getCreatePollQueryOptions = <TData = Awaited<ReturnType<typeof createPoll>>, TError = unknown>(createPollDto: CreatePollDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPoll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreatePollQueryKey(createPollDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createPoll>>> = ({ signal }) => createPoll(createPollDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createPoll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreatePollQueryResult = NonNullable<Awaited<ReturnType<typeof createPoll>>>
export type CreatePollQueryError = unknown


export function useCreatePoll<TData = Awaited<ReturnType<typeof createPoll>>, TError = unknown>(
 createPollDto: CreatePollDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPoll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createPoll>>,
          TError,
          Awaited<ReturnType<typeof createPoll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatePoll<TData = Awaited<ReturnType<typeof createPoll>>, TError = unknown>(
 createPollDto: CreatePollDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPoll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createPoll>>,
          TError,
          Awaited<ReturnType<typeof createPoll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatePoll<TData = Awaited<ReturnType<typeof createPoll>>, TError = unknown>(
 createPollDto: CreatePollDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPoll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Launch a poll
 */

export function useCreatePoll<TData = Awaited<ReturnType<typeof createPoll>>, TError = unknown>(
 createPollDto: CreatePollDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPoll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreatePollQueryOptions(createPollDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getClosePollUrl = (id: string,) => {




  return `/api/studio/polls/${id}/close`
}

/**
 * @summary Close a poll
 */
export const closePoll = async (id: string, options?: RequestInit): Promise<PollResponseDto> => {

  return customFetch<PollResponseDto>(getClosePollUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getClosePollQueryKey = (id: string,) => {
    return [
    'POST', `/api/studio/polls/${id}/close`
    ] as const;
    }


export const getClosePollQueryOptions = <TData = Awaited<ReturnType<typeof closePoll>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof closePoll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClosePollQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof closePoll>>> = ({ signal }) => closePoll(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof closePoll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClosePollQueryResult = NonNullable<Awaited<ReturnType<typeof closePoll>>>
export type ClosePollQueryError = unknown


export function useClosePoll<TData = Awaited<ReturnType<typeof closePoll>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof closePoll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof closePoll>>,
          TError,
          Awaited<ReturnType<typeof closePoll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClosePoll<TData = Awaited<ReturnType<typeof closePoll>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof closePoll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof closePoll>>,
          TError,
          Awaited<ReturnType<typeof closePoll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClosePoll<TData = Awaited<ReturnType<typeof closePoll>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof closePoll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Close a poll
 */

export function useClosePoll<TData = Awaited<ReturnType<typeof closePoll>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof closePoll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClosePollQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getSetPinnedTopicUrl = () => {




  return `/api/studio/pin`
}

/**
 * @summary Set pinned topic
 */
export const setPinnedTopic = async (pinTopicDto: PinTopicDto, options?: RequestInit): Promise<PinnedTopicResponseDto> => {

  return customFetch<PinnedTopicResponseDto>(getSetPinnedTopicUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pinTopicDto)
  }
);}





export const getSetPinnedTopicQueryKey = (pinTopicDto?: PinTopicDto,) => {
    return [
    'POST', `/api/studio/pin`, pinTopicDto
    ] as const;
    }


export const getSetPinnedTopicQueryOptions = <TData = Awaited<ReturnType<typeof setPinnedTopic>>, TError = unknown>(pinTopicDto: PinTopicDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof setPinnedTopic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSetPinnedTopicQueryKey(pinTopicDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof setPinnedTopic>>> = ({ signal }) => setPinnedTopic(pinTopicDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof setPinnedTopic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SetPinnedTopicQueryResult = NonNullable<Awaited<ReturnType<typeof setPinnedTopic>>>
export type SetPinnedTopicQueryError = unknown


export function useSetPinnedTopic<TData = Awaited<ReturnType<typeof setPinnedTopic>>, TError = unknown>(
 pinTopicDto: PinTopicDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof setPinnedTopic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof setPinnedTopic>>,
          TError,
          Awaited<ReturnType<typeof setPinnedTopic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSetPinnedTopic<TData = Awaited<ReturnType<typeof setPinnedTopic>>, TError = unknown>(
 pinTopicDto: PinTopicDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof setPinnedTopic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof setPinnedTopic>>,
          TError,
          Awaited<ReturnType<typeof setPinnedTopic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSetPinnedTopic<TData = Awaited<ReturnType<typeof setPinnedTopic>>, TError = unknown>(
 pinTopicDto: PinTopicDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof setPinnedTopic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Set pinned topic
 */

export function useSetPinnedTopic<TData = Awaited<ReturnType<typeof setPinnedTopic>>, TError = unknown>(
 pinTopicDto: PinTopicDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof setPinnedTopic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSetPinnedTopicQueryOptions(pinTopicDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getPostBoothChatUrl = () => {




  return `/api/studio/chat`
}

/**
 * @summary Post booth chat
 */
export const postBoothChat = async (boothChatDto: BoothChatDto, options?: RequestInit): Promise<ChatMessageResponseDto> => {

  return customFetch<ChatMessageResponseDto>(getPostBoothChatUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(boothChatDto)
  }
);}





export const getPostBoothChatQueryKey = (boothChatDto?: BoothChatDto,) => {
    return [
    'POST', `/api/studio/chat`, boothChatDto
    ] as const;
    }


export const getPostBoothChatQueryOptions = <TData = Awaited<ReturnType<typeof postBoothChat>>, TError = unknown>(boothChatDto: BoothChatDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postBoothChat>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostBoothChatQueryKey(boothChatDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postBoothChat>>> = ({ signal }) => postBoothChat(boothChatDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postBoothChat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostBoothChatQueryResult = NonNullable<Awaited<ReturnType<typeof postBoothChat>>>
export type PostBoothChatQueryError = unknown


export function usePostBoothChat<TData = Awaited<ReturnType<typeof postBoothChat>>, TError = unknown>(
 boothChatDto: BoothChatDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postBoothChat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postBoothChat>>,
          TError,
          Awaited<ReturnType<typeof postBoothChat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostBoothChat<TData = Awaited<ReturnType<typeof postBoothChat>>, TError = unknown>(
 boothChatDto: BoothChatDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postBoothChat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postBoothChat>>,
          TError,
          Awaited<ReturnType<typeof postBoothChat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostBoothChat<TData = Awaited<ReturnType<typeof postBoothChat>>, TError = unknown>(
 boothChatDto: BoothChatDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postBoothChat>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Post booth chat
 */

export function usePostBoothChat<TData = Awaited<ReturnType<typeof postBoothChat>>, TError = unknown>(
 boothChatDto: BoothChatDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postBoothChat>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostBoothChatQueryOptions(boothChatDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateStationSessionUrl = () => {




  return `/api/studio/session`
}

/**
 * @summary Start a cookie-based station session
 */
export const createStationSession = async ( options?: RequestInit): Promise<StudioSessionResponseDto> => {

  return customFetch<StudioSessionResponseDto>(getCreateStationSessionUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCreateStationSessionQueryKey = () => {
    return [
    'POST', `/api/studio/session`
    ] as const;
    }


export const getCreateStationSessionQueryOptions = <TData = Awaited<ReturnType<typeof createStationSession>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateStationSessionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createStationSession>>> = ({ signal }) => createStationSession({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createStationSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateStationSessionQueryResult = NonNullable<Awaited<ReturnType<typeof createStationSession>>>
export type CreateStationSessionQueryError = unknown


export function useCreateStationSession<TData = Awaited<ReturnType<typeof createStationSession>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createStationSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createStationSession>>,
          TError,
          Awaited<ReturnType<typeof createStationSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateStationSession<TData = Awaited<ReturnType<typeof createStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createStationSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createStationSession>>,
          TError,
          Awaited<ReturnType<typeof createStationSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateStationSession<TData = Awaited<ReturnType<typeof createStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Start a cookie-based station session
 */

export function useCreateStationSession<TData = Awaited<ReturnType<typeof createStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateStationSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetStationSessionUrl = () => {




  return `/api/studio/session`
}

/**
 * @summary Check the station session status
 */
export const getStationSession = async ( options?: RequestInit): Promise<StudioSessionStatusResponseDto> => {

  return customFetch<StudioSessionStatusResponseDto>(getGetStationSessionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStationSessionQueryKey = () => {
    return [
    `/api/studio/session`
    ] as const;
    }


export const getGetStationSessionQueryOptions = <TData = Awaited<ReturnType<typeof getStationSession>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStationSessionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStationSession>>> = ({ signal }) => getStationSession({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStationSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStationSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getStationSession>>>
export type GetStationSessionQueryError = unknown


export function useGetStationSession<TData = Awaited<ReturnType<typeof getStationSession>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStationSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStationSession>>,
          TError,
          Awaited<ReturnType<typeof getStationSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStationSession<TData = Awaited<ReturnType<typeof getStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStationSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStationSession>>,
          TError,
          Awaited<ReturnType<typeof getStationSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStationSession<TData = Awaited<ReturnType<typeof getStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check the station session status
 */

export function useGetStationSession<TData = Awaited<ReturnType<typeof getStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStationSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getClearStationSessionUrl = () => {




  return `/api/studio/session`
}

/**
 * @summary Clear the station session cookie
 */
export const clearStationSession = async ( options?: RequestInit): Promise<StudioSessionClearResponseDto> => {

  return customFetch<StudioSessionClearResponseDto>(getClearStationSessionUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getClearStationSessionQueryKey = () => {
    return [
    'DELETE', `/api/studio/session`
    ] as const;
    }


export const getClearStationSessionQueryOptions = <TData = Awaited<ReturnType<typeof clearStationSession>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clearStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClearStationSessionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clearStationSession>>> = ({ signal }) => clearStationSession({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clearStationSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClearStationSessionQueryResult = NonNullable<Awaited<ReturnType<typeof clearStationSession>>>
export type ClearStationSessionQueryError = unknown


export function useClearStationSession<TData = Awaited<ReturnType<typeof clearStationSession>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clearStationSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clearStationSession>>,
          TError,
          Awaited<ReturnType<typeof clearStationSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClearStationSession<TData = Awaited<ReturnType<typeof clearStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clearStationSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clearStationSession>>,
          TError,
          Awaited<ReturnType<typeof clearStationSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClearStationSession<TData = Awaited<ReturnType<typeof clearStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clearStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Clear the station session cookie
 */

export function useClearStationSession<TData = Awaited<ReturnType<typeof clearStationSession>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clearStationSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClearStationSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






