/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Wildcat Radio v2 API
 * Control plane — see docs/final-build-plan/03-API-CONTRACT.md
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AttendanceControllerListParams,
  AttendanceRowDto,
  CorrectAttendanceDto,
  CreateAttendanceDto,
  DecideOvertimeDto
} from '../../model';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getAttendanceControllerListUrl = (params: AttendanceControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/attendance?${stringifiedParams}` : `/api/attendance`
}

/**
 * @summary Get attendance sheet for a date, optionally filtered by show
 */
export const attendanceControllerList = async (params: AttendanceControllerListParams, options?: RequestInit): Promise<AttendanceRowDto[]> => {

  return customFetch<AttendanceRowDto[]>(getAttendanceControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAttendanceControllerListQueryKey = (params?: AttendanceControllerListParams,) => {
    return [
    `/api/attendance`, ...(params ? [params] : [])
    ] as const;
    }


export const getAttendanceControllerListQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerList>>, TError = unknown>(params: AttendanceControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerList>>> = ({ signal }) => attendanceControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerList>>>
export type AttendanceControllerListQueryError = unknown


export function useAttendanceControllerList<TData = Awaited<ReturnType<typeof attendanceControllerList>>, TError = unknown>(
 params: AttendanceControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerList>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerList<TData = Awaited<ReturnType<typeof attendanceControllerList>>, TError = unknown>(
 params: AttendanceControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerList>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerList<TData = Awaited<ReturnType<typeof attendanceControllerList>>, TError = unknown>(
 params: AttendanceControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get attendance sheet for a date, optionally filtered by show
 */

export function useAttendanceControllerList<TData = Awaited<ReturnType<typeof attendanceControllerList>>, TError = unknown>(
 params: AttendanceControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getAttendanceControllerCreateUrl = () => {




  return `/api/attendance`
}

/**
 * @summary Create attendance for a scheduled occurrence that currently has no record
 */
export const attendanceControllerCreate = async (createAttendanceDto: CreateAttendanceDto, options?: RequestInit): Promise<AttendanceRowDto> => {

  return customFetch<AttendanceRowDto>(getAttendanceControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAttendanceDto)
  }
);}





export const getAttendanceControllerCreateQueryKey = (createAttendanceDto?: CreateAttendanceDto,) => {
    return [
    'POST', `/api/attendance`, createAttendanceDto
    ] as const;
    }


export const getAttendanceControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerCreate>>, TError = unknown>(createAttendanceDto: CreateAttendanceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerCreateQueryKey(createAttendanceDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerCreate>>> = ({ signal }) => attendanceControllerCreate(createAttendanceDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCreate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerCreate>>>
export type AttendanceControllerCreateQueryError = unknown


export function useAttendanceControllerCreate<TData = Awaited<ReturnType<typeof attendanceControllerCreate>>, TError = unknown>(
 createAttendanceDto: CreateAttendanceDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCreate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerCreate<TData = Awaited<ReturnType<typeof attendanceControllerCreate>>, TError = unknown>(
 createAttendanceDto: CreateAttendanceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCreate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerCreate<TData = Awaited<ReturnType<typeof attendanceControllerCreate>>, TError = unknown>(
 createAttendanceDto: CreateAttendanceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create attendance for a scheduled occurrence that currently has no record
 */

export function useAttendanceControllerCreate<TData = Awaited<ReturnType<typeof attendanceControllerCreate>>, TError = unknown>(
 createAttendanceDto: CreateAttendanceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerCreateQueryOptions(createAttendanceDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getAttendanceControllerCorrectUrl = (recordId: string,) => {




  return `/api/attendance/${recordId}`
}

/**
 * @summary Correct an attendance record (time in/out, note)
 */
export const attendanceControllerCorrect = async (recordId: string,
    correctAttendanceDto: CorrectAttendanceDto, options?: RequestInit): Promise<AttendanceRowDto> => {

  return customFetch<AttendanceRowDto>(getAttendanceControllerCorrectUrl(recordId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(correctAttendanceDto)
  }
);}





export const getAttendanceControllerCorrectQueryKey = (recordId: string,
    correctAttendanceDto?: CorrectAttendanceDto,) => {
    return [
    'PATCH', `/api/attendance/${recordId}`, correctAttendanceDto
    ] as const;
    }


export const getAttendanceControllerCorrectQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError = unknown>(recordId: string,
    correctAttendanceDto: CorrectAttendanceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerCorrectQueryKey(recordId,correctAttendanceDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerCorrect>>> = ({ signal }) => attendanceControllerCorrect(recordId,correctAttendanceDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: recordId !== null && recordId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerCorrectQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerCorrect>>>
export type AttendanceControllerCorrectQueryError = unknown


export function useAttendanceControllerCorrect<TData = Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError = unknown>(
 recordId: string,
    correctAttendanceDto: CorrectAttendanceDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerCorrect>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerCorrect>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerCorrect<TData = Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError = unknown>(
 recordId: string,
    correctAttendanceDto: CorrectAttendanceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerCorrect>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerCorrect>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerCorrect<TData = Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError = unknown>(
 recordId: string,
    correctAttendanceDto: CorrectAttendanceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Correct an attendance record (time in/out, note)
 */

export function useAttendanceControllerCorrect<TData = Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError = unknown>(
 recordId: string,
    correctAttendanceDto: CorrectAttendanceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerCorrect>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerCorrectQueryOptions(recordId,correctAttendanceDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getAttendanceControllerDecideOvertimeUrl = (recordId: string,) => {




  return `/api/attendance/${recordId}/overtime`
}

/**
 * @summary Approve or revoke completed DJ overtime
 */
export const attendanceControllerDecideOvertime = async (recordId: string,
    decideOvertimeDto: DecideOvertimeDto, options?: RequestInit): Promise<AttendanceRowDto> => {

  return customFetch<AttendanceRowDto>(getAttendanceControllerDecideOvertimeUrl(recordId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(decideOvertimeDto)
  }
);}





export const getAttendanceControllerDecideOvertimeQueryKey = (recordId: string,
    decideOvertimeDto?: DecideOvertimeDto,) => {
    return [
    'POST', `/api/attendance/${recordId}/overtime`, decideOvertimeDto
    ] as const;
    }


export const getAttendanceControllerDecideOvertimeQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError = unknown>(recordId: string,
    decideOvertimeDto: DecideOvertimeDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerDecideOvertimeQueryKey(recordId,decideOvertimeDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>> = ({ signal }) => attendanceControllerDecideOvertime(recordId,decideOvertimeDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: recordId !== null && recordId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerDecideOvertimeQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>>
export type AttendanceControllerDecideOvertimeQueryError = unknown


export function useAttendanceControllerDecideOvertime<TData = Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError = unknown>(
 recordId: string,
    decideOvertimeDto: DecideOvertimeDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerDecideOvertime<TData = Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError = unknown>(
 recordId: string,
    decideOvertimeDto: DecideOvertimeDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerDecideOvertime<TData = Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError = unknown>(
 recordId: string,
    decideOvertimeDto: DecideOvertimeDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Approve or revoke completed DJ overtime
 */

export function useAttendanceControllerDecideOvertime<TData = Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError = unknown>(
 recordId: string,
    decideOvertimeDto: DecideOvertimeDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerDecideOvertime>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerDecideOvertimeQueryOptions(recordId,decideOvertimeDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






